### PR TITLE
Cas 11504 bug fix improved bin accounting for quantile computations

### PR DESCRIPTION
**Pull request by dmehring**
* change type of nBins uInt64 -> uInt (shouldn't need more than 2e9 bins, ever!)
* add C++11 features
* add useful typedefs

### CODE REVIEW

**Comment by mpokorny** [comment]
Dave, it looks like you may have gotten ahead of #737 with your c++11-only additions. I guess that it's my fault, since I told you it was OK to proceed with c++11-only changes. I expect merging #737 will happen soon, but please let me know if this becomes urgent.

**Comment by dmehring** [comment]
Hi Martin
Yes I thought that C++11 features had been green lighted. 

It looks like the 737 changes are relatively small, so hopefully that will be merged relatively soon. 

I do gather that from a pipeline POV, my fix is pretty important.

**Comment by tammojan** [comment]
Feel free to ignore the failing Travis CXX98 when reviewing this pull request (it's the only failing build, the others went through fine).

**Comment by dmehring** [comment]
Thanks Martin.

**Pull request merged**
