### PR TITLE
fixed constness in LatticeCleaner<T>::setMask parameter

### PR DESCRIPTION
**Pull request by VoronkovMA**
This is a trivial pull request fixing constness in LatticeCleaner<T>::setMask input parameter. The method doesn't change the input mask lattice (and shouldn't conceptually), so having it passed via const reference (i.e. the same way as it is done for the dirty image and PSF) seems to be more appropriate.

I've also done few minor tweaks to the body of the method which do not alter the functionality (making use of previously unused variables).

P.S. I also noticed that MultiTermLatticeCleaner class has a bit of technical debt / needs some work, if it is working at all (in contrast to LatticeCleaner we don't use it in ASKAPsoft and reimplemented the same algorithm some other way, probably for a reason). Although this class is derived from LatticeCleaner, it does not override setMask method but has a setmask one instead (i.e. all low-case). Ignoring the fact that this is an untidy design, it means that my change suggested in this pull request has no impact. Although a number of methods of MultiTermLatticeCleaner also accept non-const references for no good reason, I decided to leave it as is for now, especially because there seem to be no unit tests for it.

### CODE REVIEW

**Review by tammojan — APPROVED** [review]
Looks good to me, thanks.

**Comment by VoronkovMA** [comment]
@tammojan what is the issue with macOS CI build which fails and presumably prevents the merge? Due to the simplicity of the changes in this PR, I somehow doubt it is due to my changes.

**Comment by rtobar** [comment]
@VoronkovMA it should be this: https://github.com/casacore/casacore/pull/1327

**Comment by VoronkovMA** [comment]
I took changes from casacore:master onto the pull request branch to fix CI issues, this seems to have worked.

**Pull request merged**
