### PR TITLE
CAS-3660 bug fix for gaps in AN table, better error handling

### PR DESCRIPTION
**Pull request by dmehring**
Cleaned up logic in the method to write the ANTENNA table including defect fixes and better error handling and logging. Refactored common code into a method of its own. Other refactoring. Since I'm the only one working on these files now, I'm using the industry standard _ prefix for private fields and methods. I will slowly be migrating existing fields to this format as I continue refactoring this code.

### CODE REVIEW

**Comment by juliantaylor** [comment]
_prefix is only a "industry standard" in some languages like python.
In C underscore followed by capital letter are reserved keywords of the language.

for c++ it doesn't matter due to namespaces, but the casa(core?) convention for private fields is a `_p` suffix

**Comment by juliantaylor** [comment]
oh `_p` is just members not functions

**Comment by dmehring** [comment]
So ... you're not going to merge it because of that? Note there are private fields (not created by me) in this same file that do not follow such a pattern.

Can you point me to the document that defines casacore code standards please? Thanks.

**Comment by juliantaylor** [comment]
I am just pointing out that you are introducing inconsistencies, even within the same file
its not much of a document but there is this: https://safe.nrao.edu/wiki/bin/view/Software/CASA/CasaCoreInfo#Coding_Style
which says either `_p` suffix or `its` prefix.
I don't mind either approach, but it would be good to not mix the two in the same subsystem.

Also please split bug fixes from pure style changes in different commits to make reviewing easier.

**Comment by dmehring** [comment]
I'm going to be working on these files a lot, so my goal is that in the end they will be consistent. Apologies if that wasn't clear in my commit comment. I can't make all the style changes in one go in a several thousand line file, and it would be a nightmare to review anyway if I did. 

I did two git add -p to try to separate things to make it easier to review as you had requested previously. Unfortunately, it is simply not effecient to purely seperate style changes from functionality changes; sometimes if I don't make style changes simultaneously with functional changes, style changes simply won't get made.

**Comment by juliantaylor** [comment]
fair enough, the changes do look like the improve the code a lot.
thanks

**Comment by dmehring** [comment]
Thanks!

**Pull request merged**
