### PR TITLE
bug fix, exposure times were incorrectly being used as intervals

### PR DESCRIPTION
**Pull request by dmehring**

### CODE REVIEW

**Comment by juliantaylor** [comment]
urg that should have been spotted by review, sloppy me ...

**Comment by dmehring** [comment]
Thanks. Given that I coded the bug, I cannot pass judgement on any one else for not spotting it :) .

**Comment by juliantaylor** [comment]
@tammojan just made a release for other projects a few hours ago.
but this doesn't look like its necessarily a big problem as it deals with a new feature for casa specific data right?

**Comment by dmehring** [comment]
I suspect it does not pose a major issue for other groups, but not knowing the extent of which they use this and related classes nor the details of their data sets (in ours exposure times and intervals are often the same or very close to being equal, so for us this isn't a big problem), I cannot say for certain to the degree others might be affected.

**Pull request merged**
