### PR TITLE
Bug fix in PolnParse and feature addition in FIELD and SPW selection

### PR DESCRIPTION
**Pull request by sanbw**
This PR has fix in MSPolnParse.cc for index overrun bug.  

I have also merged code from CAS-12049 which brings feature additions to field and SPW selection.  An integer for field or SPW selection which is greater than the total number of rows in the sub-tables is matched as a string against the NAME columns.  This allows naming fields or SPWs with names that parse as valid integers greater than total number of sub-table rows.  Nothing changes for integer specifications less than the total number of rows in the sub-tables (i.e., that works as before).  I have also added tMSSelection2.{run,out} with an associated MS to test the new features.

### CODE REVIEW

**Comment by gervandiepen** [comment]
Did you add the new tMSSelection2 to CMakeListst.txt? I don't see such a change.

**Comment by sanbw** [comment]
Apologies.  I forgot to make that change in CMakeListst.txt.  will do so
soon.

____________
Extra typos due to Pixel between small keys and thick fingers.

**Comment by sanbw** [comment]
Ger,
I added tMSSelection2.{run,out} as the new regressions that use the tMSSelection executable.  So I don't need to add anything new to build in CMakeLists.txt.  However I am not sure what to change, if anything, to make sure tMSSelection2.run is also used as part of the regression suite.

**Comment by gervandiepen** [comment]
You have to add the test without doing a build of a program. So only add the add_test line like
  add_test (tMSSelection2 ${CMAKE_SOURCE_DIR}/cmake/cmake_assay ./tMSSelection2)
at the end of MSSel/test/CMakeLists.txt.
See also for example TaQL/test/CMakeLists.txt which has multiple 'script-only' tests.

**Comment by sanbw** [comment]
I just added tMSSelection2 regression in the ms/MSSel/CMakeLists.txt.  I tested it locally as:

```
sbhatnag@dhruva>ctest -R tMSSelection
Test project /home/dhruva/disk2/sanjay/casa_rhel/BitBucket/ARD/ARD-3/casa/casacore/casacore/build-linux_64b
    Start 390: tMSSelection
1/2 Test #390: tMSSelection .....................   Passed    1.69 sec
    Start 391: tMSSelection2
2/2 Test #391: tMSSelection2 ....................   Passed    0.29 sec

100% tests passed, 0 tests failed out of 2

Total Test time (real) =   1.99 sec


```

**Comment by sanbw** [comment]
Thanks Ger. Are we ready to merge mssel-errors to master now?

**Comment by gervandiepen** [comment]
Hi Sanjay,

It has been merged.

Ger

**Comment by sanbw** [comment]
Thanks Ger.

There is also a PR on casacore-notes that needs to be serviced too.

Regards,
sanjay

**Pull request merged**
