### PR TITLE
Cas 8837 implement multithreading in ClassicalStatistics::_createDataArrays

### PR DESCRIPTION
**Pull request by dmehring**

### CODE REVIEW

**Comment by juliantaylor** [comment]
please rebase the branch onto upstream/master and push -f it again to your fork

    git checkout CAS-8837
    git fetch upstream # assuming upstream is your origin remote name
    git rebase upstream/master
    git push -f fork CAS-8837

**Comment by dmehring** [comment]
git rebase produced a three-way merge conflict in apps/taql.cc (obviously a file I didn't modify) so I just skipped it. git seems confused about "fork" in the push command:

git push -f fork CAS-8837
fatal: 'fork' does not appear to be a git repository
fatal: The remote end hung up unexpectedly

do I need the "fork" in that command?

**Comment by juliantaylor** [comment]
fork is the name of your remote located on github, I don't know how you have named it (maybe origin?)

if you got a merge conflict your head was not equal to what you have pushed, it rebases for me without issues, try `git checkout e342a6a` instead

**Comment by dmehring** [comment]
1333 dmehring@legolas:$ git remote -v
GithubCasacore	https://dmehring@github.com/dmehring/casacore.git (fetch)
GithubCasacore	https://dmehring@github.com/dmehring/casacore.git (push)
origin	ssh://git@github.com/dmehring/casacore (fetch)
origin	ssh://git@github.com/dmehring/casacore (push)

I used "origin" for "upstream" in git fetch upstream since the two remotes point to the same place, just with different protocols.

**Comment by juliantaylor** [comment]
you need a remote pointing to casacore/casacore and you need to rebase on top of that remotes master
also assuming your paste is complete, you are not using git-prompt? it is absolutely essential for using git from the commandline, please set it up (https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh)

**Comment by dmehring** [comment]
The file I copy and paste my set up from overwrote the relevant remote. Hopefully this worked now:

[dmehring@legolas casacore (master)]$ git checkout CAS-8837
Branch CAS-8837 set up to track remote branch CAS-8837 from origin.
Switched to a new branch 'CAS-8837'

[dmehring@legolas casacore (CAS-8837)]$ git remote -v
GithubCasacore	git://github.com/casacore/casacore (fetch)
GithubCasacore	git://github.com/casacore/casacore (push)
origin	ssh://git@github.com/dmehring/casacore (fetch)
origin	ssh://git@github.com/dmehring/casacore (push)

[dmehring@legolas casacore (CAS-8837)]$ git fetch GithubCasacore

[dmehring@legolas casacore (CAS-8837)]$ git rebase GithubCasacore/master
First, rewinding head to replay your work on top of it...
Applying: uInt -> uInt64 as it should have been
Applying: refactor code to be threaded into _computeDataArrays()
Applying: implement multithreading in _createDataArrays()
Applying: remove per-thread iterators and related vars from object scope
Applying: move include PtrHolder from .h to .tcc file

[dmehring@legolas casacore (CAS-8837)]$ git push -f origin CAS-8837
Counting objects: 62, done.
Delta compression using up to 16 threads.
Compressing objects: 100% (42/42), done.
Writing objects: 100% (44/44), 14.04 KiB, done.
Total 44 (delta 35), reused 6 (delta 2)
To ssh://git@github.com/dmehring/casacore
 + e342a6a...d004997 CAS-8837 -> CAS-8837 (forced update)

**Pull request merged**
