### PR TITLE
Remove notice and link

### PR DESCRIPTION
**Pull request by aroffringa**
According to @gervandiepen (in https://github.com/casacore/casacore/issues/896) this functionality is unused.
This PR changes the behaviour of RecordFieldPtr. Some tests in
Record and RecordField explicitly check for this behaviour, and therefore
fail currently, but all other tests still succeed. It should be checked if this is ok
before merging.

This is #1096, but on the casacore repos instead of my own.

### CODE REVIEW

**Comment by gervandiepen** [comment]
I've looked briefly at the changes. Next week I'll do a more detailed review.
One question. Has it been checked with the CASA group that BUILD_DEPRECATED (and the old source files) can be removed?

**Comment by aroffringa** [comment]
It hasn't -- who to ask? Maybe @cquike ?

**Comment by gervandiepen** [comment]
Probably he is a good candidate as he is contributing most from the CASA group.

**Comment by tammojan** [comment]
@cquike If you don't object, I'll merge this one in a few days.

**Comment by cquike** [comment]
Hi @tammojan : yes, please go ahead. The CASA team is indeed not aware of any potential problem that this change might cause.
Thanks for checking!

**Comment by gervandiepen** [comment]
No further review comments.

**Review by gervandiepen — APPROVED** [review]

**Pull request merged**
