### PR TITLE
CAS-5492: Add overwrite option to writeFITSFile()

### PR DESCRIPTION
**Pull request by dmehring**
Allow users the option of overwriting an existing file

### CODE REVIEW

**Comment by dpetry** [comment]
I will merge this now. Could you maybe add a case to the relevant unit test which exercises this?

**Comment by dmehring** [comment]
I've written a unit test and pushed it on the same branch but it does not show up in the diffs. Does the pull request have to be open in order for further changes to be made?

**Comment by tammojan** [comment]
Yes it does. Probably easiest is to make a new pull request (once a PR has been merged, it cannot be reopened).

**Comment by dmehring** [comment]
Open PR 308.

**Pull request merged**
