### PR TITLE
Fixing issue 265

### PR DESCRIPTION
**Pull request by vsuorant**

### CODE REVIEW

**Comment by juliantaylor** [comment]
I always though that was intentional given its the only compiler warning casacore produces. Interesting it actually causes issues somehow.
A better commit message would be good explaining how it is related to the issue (which can be automatically closed via `Closes gh-265`)

**Comment by vsuorant** [comment]
I updated the commit message. I think Ger needs to take a look at this before this gets merged to master. It fixes the issue for me and doesn't seem to cause any harm, but I don't know if this is logically the correct thing to do.

**Comment by gervandiepen** [comment]
I'll look into it. The old code is clearly wrong, thus the change is an improvement, but I have to make sure it works fine for a String or Bool key.

**Comment by gervandiepen** [comment]
It is only used for Int64 and Double, thus the fix is fine.

**Pull request merged**
