### PR TITLE
Array align init2

### PR DESCRIPTION
**Pull request by ithubg**
This request includes a fix to suppress warnings for non-virtual destructor and other fixes.

### CODE REVIEW

**Comment by ithubg** [comment]
Please merge to master because this request suppress the warnings like below which should be ignored.

/var/rpmbuild/BUILD/casa-test/casa-test-4.5.59/casacore/casacore/casa/Containers/Block.h:715: warning: 'struct casa::Block<bool>::BulkAllocatorImpl<casa::std11_allocator<bool> >' has virtual functions but non-virtual destructor

**Comment by juliantaylor** [comment]
can you squash the commits into one please, it is very useful to have every commit pass the tests for bisections, especially as this deals with memory allocations.

    git rebase -i 3f2bf4bfa9464d036d772fcca0160202999f1a8a

**Comment by ithubg** [comment]
Thanks a lot!
I have squashed the commits into one.

**Comment by ithubg** [comment]
This pull request was recreated as #177.

**Pull request closed without merging**
