### PR TITLE
Move back to maia.usno.navy.mil for measures data

### PR DESCRIPTION
**Pull request by tammojan**
Work done by Arno Schoenmakers

### CODE REVIEW

**Comment by dpetry** [comment]
@tammojan , this is only temporary, right? Once the IERS services are up again, this will be reverted, correct?

**Comment by tammojan** [comment]
I don't know why IERS is down (and why the maia server is up!), if IERS comes back we could switch back. It would be good to keep the change that allows https in that case.

**Comment by dpetry** [comment]
IERS is down because of maintenance. MAIA was down because of a website upgrade which is completed now.
Ideally, our system should try to use MAIA if IERS is down.

**Comment by dpetry** [comment]
If the fall-back feature could be implemented now, that would be good because now we have a moment where we can test it. I suspect IERS is going to be up again soon.

**Comment by dpetry** [comment]
However, looking at the code, I don't see a simple way of implementing a fall-back. Do you?

**Comment by tammojan** [comment]
No, I think implementing a fall-back in this code will be hard.

**Comment by tammojan** [comment]
Thanks for the review + merge @dpetry! Let's move back to iers.org once the maia server gives problems again..

**Pull request merged**
