### PR TITLE
Issue #91: Added CMake version checking for wcslib and cfitsio

### PR DESCRIPTION
**Pull request by tammojan**
Added some code to FindWCSLIB and FindCFITSIO that finds their version (by a regexp on an include file). Then CMake can find out if the version is recent enough.

### CODE REVIEW

**Comment by tammojan** [comment]
Travis reports an error because it has wcslib 4.8 and I set the minimum to 4.20. Is 4.20 really required? I'll check manually with 4.8.3.

**Comment by gijzelaerr** [comment]
Well done Tammo, your first pull request ;)

I think this set of commits are a perfect candidate for squashing (merging together).

```
$ rebase -i 2a651e31c8d1c51a72a6eea5fcf224b0d7c26207  # the sha1 ID of the last commit before your changes
```

This will open up a editor where you can squash commits. Just replace all the `pick` with an `s`, except the one on the first line. Save the file, rewrite your commit message and force push your changes to your branch again:
```
$ git push -f
```

**Comment by gijzelaerr** [comment]
i've uploaded a WCSLIB `4.25.1-3precise` package to the launchpad PPA so I think it should pick that one up?

**Comment by gijzelaerr** [comment]
Yes, `4.20` is required, or at least that is the lowest confirmed version. Some of the tests fail if you use `4.8`

**Comment by tammojan** [comment]
Bedankt voor de cursus git... Ik kom er nog niet uit:

git rebase -i 2a651e31c8d1c51a72a6eea5fcf224b0d7c26207
# Not currently on any branch.
nothing to commit (working directory clean)

Could not apply 668d54b... Revert "Added CMake version checking for wcslib and cfitsio", almost ruined 2.0.1 again

**Comment by gijzelaerr** [comment]
are you in your issue91 branch?

**Comment by tammojan** [comment]
Yes I am.

dijkema@lhd002:~/opt/casacore/tammojan/casacore$ git status
# On branch issue91
nothing to commit (working directory clean)
dijkema@lhd002:~/opt/casacore/tammojan/casacore$ git rebase -i 2a651e31c8d1c51a72a6eea5fcf224b0d7c26207 
# Not currently on any branch.
nothing to commit (working directory clean)

Could not apply 668d54b... Revert "Added CMake version checking for wcslib and cfitsio", almost ruined 2.0.1 again

dijkema@lhd002:~/opt/casacore/tammojan/casacore$ git status
# Not currently on any branch.
nothing to commit (working directory clean)
dijkema@lhd002:~/opt/casacore/tammojan/casacore$ git checkout issue91
Previous HEAD position was 2a651e3... prepare for 2.0.1
Switched to branch 'issue91'
dijkema@lhd002:~/opt/casacore/tammojan/casacore$ git status
# On branch issue91
nothing to commit (working directory clean)
dijkema@lhd002:~/opt/casacore/tammojan/casacore$ git rebase --abort
dijkema@lhd002:~/opt/casacore/tammojan/casacore$ git rebase -i 2a651e31c8d1c51a72a6eea5fcf224b0d7c26207 
Cannot 'squash' without a previous commit
dijkema@lhd002:~/opt/casacore/tammojan/casacore$ git rebase --abort
dijkema@lhd002:~/opt/casacore/tammojan/casacore$ git rebase -i 2a651e31c8d1c51a72a6eea5fcf224b0d7c26207 
# Not currently on any branch.
nothing to commit (working directory clean)

Could not apply 668d54b... Revert "Added CMake version checking for wcslib and cfitsio", almost ruined 2.0.1 again

**Comment by tammojan** [comment]
Closing this pull request and building a new one (because of some merge conflicts).

**Pull request closed without merging**
