### PR TITLE
Additional Adios2StMan I/O patterns, part 2

### PR DESCRIPTION
**Pull request by rtobar**
This PR adds new I/O pattern support to Adios2StMan on top of those added in #966. This turned out to be the final set of changes that allowed us to achieved pretty good writing performance in our SUMMIT experiments (~130 GB/s with 1k writers).

In this PR I'm reverting the work merged in two previous PRs: #943 (reading cache) and #957 (changing the default ADIOS2 engine).  These PRs were introduced with the aim of increasing the performance of Adios2StMan, but they were not used in the experiments, and hence they don't demonstrably improve things. More details in 4d4c9e2.

The main changes in terms of additional I/O patterns is about supporting the get/putScalarColumnCells* methods in the storage manager (d2d01e3). The rest, apart from the main revert described above, are smaller cleanups.

cc: @JasonRuonanWang

### CODE REVIEW

**Comment by JasonRuonanWang** [comment]
Great job! Thanks Rodrigo!

@tammojan Please feel free to merge Rodrigo's future PRs on Adios2StMan as needed. I think he is doing a better job than me on this because he understands the application requirements better than me. I would like to give the ownership of Adios2StMan to him, and I will focus more on the ADIOS2 side to provide better supports addressing the requirements from the Adios2StMan layer.

**Comment by rtobar** [comment]
Failing jobs are MacOSs failing to download data due to homebrew's ssl installation apparently

**Comment by rtobar** [comment]
@tammojan a quick ping to re-activate this PR. In addition to the result reported originally, we have also seen better writing speeds occasionally (~160 GB/s with 1k writers), and have also achieved ~250 GB/s when running 3 independent sets of 1k writers at the same time to the same filesystem, and ~410 GB/s when running with 6 sets. Thanks to @JasonRuonanWang for reminding me of re-activating this thread.

**Comment by JasonRuonanWang** [comment]
@rtobar Do you have any idea why the tests are failing? Can we try to rebase and see if the problem can be fixed?

**Comment by rtobar** [comment]
@JasonRuonanWang the problem with the tests when the PR was originally created was with the MacOS images and them not being able to download some required data -- nothing to do with the changes themselves. Rebasing wouldn't help, as even [in the latest](https://travis-ci.org/github/casacore/casacore/builds/669746025) `master` branch things are still failing in MacOS; the problems now are different, but they have been affecting other PRs as well.

**Comment by JasonRuonanWang** [comment]
Okay.

@tammojan Could you please review and let us know what we need to do? Thanks.

**Comment by tammojan** [comment]
Thanks @rtobar for fixing the MacOS tests on master! I've rebased this branch on top of the passing master. When the [tests](https://travis-ci.org/github/casacore/casacore/builds/671613883) pass I will merge this PR.

**Comment by JasonRuonanWang** [comment]
@rtobar @tammojan Thanks for taking care of this.

**Pull request merged**
