### PR TITLE
Enable dT[T0~T1] syntax and return dT via MSSelection:getTimeList()

### PR DESCRIPTION
**Pull request by sanbw**
Time selection syntax of the type `dT[ T0~T1]` where the supplied `dT` is used to determine the boundaries for the given range was not enabled (accidentally).  With this merge, it would be enabled.

`MSSelection::getTimeList()` would return a 3xN matrix with the third element of each row containing the value for `dT `used.  Currently a 2xN matrix is return.  

Changes are in the following files:

```
> git diff --name-only origin
ms/MSSel/MSSelection.cc
ms/MSSel/MSTimeGram.yy
ms/MSSel/MSTimeParse.cc
ms/MSSel/MSTimeParse.h
ms/MSSel/test/tMSSelection.out
ms/MSSel/test/tMSSelection.run
```

### CODE REVIEW

**Comment by sanbw** [comment]
The build using clang failed (said "build errored").  Following was the reason:

> The job exceeded the maximum time limit for jobs, and has been terminated.

The build using gcc passed. 

Could someone with the required permissions check this please?  Thanks.

**Comment by tammojan** [comment]
The timeout on the clang build is almost certainly unrelated to your change. Let's fix that in #630.

As for your commits: merging the master branch into a feature branch is not good practice. Perhaps @mpokorny can help you rebase your commits such that only the relevant commits remain (I think `git rebase master` should do, but it's usually more efficient to do this with a local git wizard around).

**Comment by sanbw** [comment]
I have successfully done a `git rebase master`, but had to do a `git push -f` to push the changes back to the CAS-10142 branch on GitHub.  AFAICT, it looks OK.  Thanks @mpokorny.

**Comment by tammojan** [comment]
Apparently something went wrong again with git rebase. I cherry-picked the last commits (f78ef59, e43c230, d44bce0, f442b8a, 62bb985) and made a new branch with a new pull request in #634. Closing this one.

**Pull request closed without merging**
