### PR TITLE
Added code to MSConcat to properly merge the MS PROCESSOR table

### PR DESCRIPTION
**Pull request by dpetry**
... and reindex the Main table references to it.

### CODE REVIEW

**Comment by dpetry** [comment]
Hi @tammojan , the travis checks passed on Linux but not on Mac. Could you have a look?

**Comment by dpetry** [comment]
Hi Darrell, could you review this change?
This is for CAS-12937. I ran all relevant tests and also several manual ones which I will automate once I have this in casacore.

**Comment by dpetry** [comment]
According to a comment by Tammo earlier, the fact that the checks have failed on Mac are a Travis setup problem and not related to this code.
The checks have passed on Linux.

**Comment by tammojan** [comment]
> According to a comment by Tammo earlier, the fact that the checks have failed on Mac are a Travis setup problem and not related to this code.
> The checks have passed on Linux.

Yes, sorry about that. @steve-ord has done some work on the macos tests in #949, once there is a working build we should get it to master asap.

Still for the current PR, merging with a failing mac build is fine with me.

**Comment by dpetry** [comment]
The Linux checks are all passing.
Only Mac Travis checks are failing but according to Tammo, this is not a problem
since this change to MSConcat is not OS-dependent.
I take this as an encouragement to merge the request.

**Pull request merged**
