### PR TITLE
CAS-10543 Add workaround for SMA SYSTEM_TEMPERATURE table

### PR DESCRIPTION
**Pull request by kettenis**
FITS-IDI files from the SMA have scalar TSYS_1/2 columns instead of
array columns as required by the FITS-IDI standard.  Interpret these
as a single value that applies to all bands like we already do for
POLAA/B in the ANTENNA table.

### CODE REVIEW

**Comment by dpetry** [comment]
Hi Mark,
could you modify the WARNING text to say explicitly that the input FITSIDI file is not following the standard. E.g. TSYS_1 and TSYS_2 columns in input SYSTEM_TEMPERATURE table are scalar although FITSIDI standard requires array."
+	    << endl << "Will accommodate that by using same value for all bands." << LogIO::POST;

**Comment by kettenis** [comment]
Hi Dirk,
Turns out that if there is only a single band the column ends up being scalar anyway, even if it is specified as 1E instead of E. So I probably should drop the warning change as it appears to be incorrect.

**Comment by dpetry** [comment]
Just make sure, when you have a working fix, that it also works with "good" FITSIDI files.

**Comment by kettenis** [comment]
Yes, verified that it still works for VLBA and EVN data. Also verified that the test_imporfitsidi.py test in CASA still passes.

**Comment by dpetry** [comment]
So, should this be merged after all?

**Comment by kettenis** [comment]
Yes, please. Without it loading of single-band FITS-IDI files that conform to the standard is broken too.

**Pull request merged**
