### PR TITLE
WCS+CFITSIO versions, resolves #91

### LINKED ISSUE #91: Update CMake minimum version numbers
wcslib 4.23 seems to be the minimum requirement, cfitsio needs a reasonably recent version. These things should be checked at CMake time, not found out at compile time.

### PR DESCRIPTION
**Pull request by tammojan**

### CODE REVIEW

**Comment by tammojan** [comment]
This is a duplicate of #91 , I cannot get the pull request to link to the issue :(

**Comment by tammojan** [comment]
@gijzelaerr Travis still uses WCSLIB 4.8, apparently your update in the PPA (which PPA) didn't get through.

**Comment by gijzelaerr** [comment]
you are right. the PPA is not enabled. will enable.

It would be awesome if travis would switch to a more recent Ubuntu, or let you choose which distro/version you want to run. They are working on it, but it is not finished yet.

**Comment by tammojan** [comment]
The travis build for gcc succeeded (https://travis-ci.org/casacore/casacore/jobs/63659419), indicating that probably #86 was caused by a too old (system) wcslib. There is a remaining travis error (`tMemory`) only with clang: https://travis-ci.org/casacore/casacore/jobs/63659418

**Pull request merged**
