### PR TITLE
Revert "CAS-8497 implement modifications to uvfits AN read/write rules"

### PR DESCRIPTION
**Pull request by JimNrao**
Reverts casacore/casacore#400

### CODE REVIEW

**Comment by JimNrao** [comment]
After the PR was merged, it failed travis-ci.  The reason for failure was that the clang/cxx11=false test exceeded the allowed time.  The pre-merge tests passed, although the came build parameters took 43 minutes to run whereas for the other platforms the longest run was 34 minutes (gcc/cx11=true) whilte the two other combinations were under ten minutes.  Is this a bit of random quirkiness or is there a real problem with the changes in the PR?

**Comment by juliantaylor** [comment]
thats normal it times out often, should be fixable now as caches are available for macos, still need to look into why the current implementation does not work

**Comment by JimNrao** [comment]
I reverted it; should I just push it in again?


On 05/09/2016 04:27 PM, Julian Taylor wrote:
>
> thats normal it times out often, should be fixable now as caches are 
> available for macos, still need to look into why the current 
> implementation does not work
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub 
> <https://github.com/casacore/casacore/pull/413#issuecomment-218008652>Web 
> Bug from 
> https://github.com/notifications/beacon/AGPGtPlLjqZHy9F7MXqUpkxjm32oPktJks5p_7TBgaJpZM4IalUQ.gif
>

-- 
Jim Jacobs

phone: 835-7235
office: 301

**Comment by juliantaylor** [comment]
I don't know what you trying to archive? why the revert?

**Comment by JimNrao** [comment]
I was about to head home and didn't want to leave a broken build 
behind.  Should I just reopen the PR and merge it in again?


On 05/09/2016 04:30 PM, Julian Taylor wrote:
>
> I don't know what you trying to archive? why the revert?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub 
> <https://github.com/casacore/casacore/pull/413#issuecomment-218009321>Web 
> Bug from 
> https://github.com/notifications/beacon/AGPGtI2Ps7sp7eci20Fp9UPFEIx31-92ks5p_7WIgaJpZM4IalUQ.gif
>

-- 
Jim Jacobs

phone: 835-7235
office: 301

**Comment by juliantaylor** [comment]
you probably have to make a new one, but leave it to tomorrow instead of rushing it.

**Pull request merged**
