### PR TITLE
Replace STL-like containers by their STL counterparts

### LINKED ISSUE #118: Discussion: Replace List,Map, etc. by STL counterparts
Casacore contains classes like List, Map, OrderedMap, HashMap. They can be replaced by their STL counterparts std::list and std::map. I'm not sure if that is also true for SimpleOrderedMap used in Tables. I have to check that.
It might well be possible that these Casacore classes are used in CASA code, so they should make the change first. I don't expect it to be used in other code like LOFAR and ASKAPsoft.

### PR DESCRIPTION
**Pull request by gervandiepen**
Classes Map (and variations), List, Queue and Stack have been replaced by their STL counterparts.
These Casacore classes are not built/installed anymore unless -DBUILD_DEPRECATED is given to cmake.

Close #118

### CODE REVIEW

**Comment by dpetry** [comment]
MSConcat is making use of simpleOrderedMap a lot. Did you already look at that?

**Comment by dpetry** [comment]
OK, I looked at your changes to MSConcat and you definitely did look at it.  :)
Question: you had to define an inline function getMapValue(). Is not even this simple functionality provided by the STL map? I am wondering why we are abandoning the CASA simpleOrderedMap if the STP version offers so few features ...

**Comment by gervandiepen** [comment]
Less code to maintain and most likely better performance (certainly support
of move semantics).
I noticed, however, that one test (tRowCopier) failed with gcc-4.8, so I
have to look into that problem.

getMapValue is doing something special by returning -1 if not find.
std::map has the functions 'at' and 'find' to lookup a key. Operator[] only
works on non-const maps (unlike the Casacore Maps). I very much like that I
can now use  'for (const auto& x : myMap)'

BTW. An advantage of the Casacore Map classes was the support of a default
value that is used when a new key is defined. It made something like:
     if (value > map[key]) map[key]=value;
possible if a default value of e.g. min_int was used. std::map always has
T() as the default, so in such a case you first have to test if the key
exists.

Also note the somewhat unexpected behaviour of std::map::define which
doesn't do anything (apart from returning a reference to the value) when an
existing key with a new value is defined. No exception and no value
replacement. There is quite some discussion on stackoverflow.

**Comment by gervandiepen** [comment]
Darrell Schiebel has built and tested the CASA package using this PR. All rests pass, so it can be merged.

**Comment by AlexKurek** [comment]
I tried to use this flag in 3.1.2 and I got:

> cmake -DCMAKE_INSTALL_PREFIX=${INSTALLDIR}/casacore/ -DDATA_DIR=${INSTALLDIR}/casacore/data -DBUILD_PYTHON3=ON -DBUILD_PYTHON=OFF -DPYTHON3_EXECUTABLE=/usr/bin/python3 -DENABLE_TABLELOCKING=OFF -DUSE_OPENMP=ON -DUSE_FFTW3=TRUE -DUSE_HDF5=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="${CXX_FLAGS} -fsigned-char -DNDEBUG" -DBUILD_DEPRECATED ../src/
> 
> Parse error in command line argument: -DBUILD_DEPRECATED
> Should be: VAR:type=value
> CMake Error: No cmake script provided.
> CMake Error: Problem processing arguments. Aborting.

**Comment by tammojan** [comment]
Try with `-DBUILD_DEPRECATED=True`.

**Comment by sarrvesh** [comment]
I am facing the same issue while compiling casarest with casacore 3.2.1. I tried casarest master and 1.5.0. Following the comments above, I tried using the branch useSTL and it fails with a different error:

[ 29%] Building CXX object msvis/CMakeFiles/casa_msvis.dir/MSVis/CalVisBuffer.cc.o
In file included from /casarest/msvis/MSVis/VisBuffer.h:39:0,
                 from /casarest/msvis/MSVis/CalVisBuffer.h:32,
                 from /casarest/msvis/MSVis/CalVisBuffer.cc:28:
/casarest/msvis/MSVis/VisibilityIterator.h:566:17: error: 'ROMSColumns' does not name a type; did you mean 'MSColumns'?
   virtual const ROMSColumns& msColumns() const
                 ^~~~~~~~~~~
                 MSColumns
In file included from /casarest/msvis/MSVis/CalVisBuffer.h:32:0,
                 from /casarest/msvis/MSVis/CalVisBuffer.cc:28:
/casarest/msvis/MSVis/VisBuffer.h:644:19: error: 'ROMSColumns' does not name a type; did you mean 'MSColumns'?
     virtual const ROMSColumns & msColumns() const {
                   ^~~~~~~~~~~
                   MSColumns
msvis/CMakeFiles/casa_msvis.dir/build.make:86: recipe for target 'msvis/CMakeFiles/casa_msvis.dir/MSVis/CalVisBuffer.cc.o' failed

**Comment by schiebel** [comment]
I believe ROMSColumns has been removed. MSColumns should be used even for read-only usage.

**Comment by bennahugo** [comment]
Workaround with ```-DBUILD_DEPRECATED=True ``` as dockerfile of casacore/casarest#31

**Pull request merged**
