### PR TITLE
Integrate ROMSxxxColumns into MSxxxColumns classes

### PR DESCRIPTION
**Pull request by gervandiepen**
A few years ago the ROScalarColumn class has been merged into the ScalarColumn class to avoid having to instantiate two different objects for about the same purpose. Similarly, ROArrayColumn, ROTableColumn and ROTableVector have been merged into their counterparts.

It made it possible to merge the ROMSxxxColumn classes into the MSxxxColumn classes making the source files considerably smaller and easier to read. Also the opprtunity was taken to remove the needless default constructor calls and use attach as much as possible. It revealed an omission in one of the attach functions which has been fixed.
The old ROMS names still exist by means of a typedef. In that way existing code will still built well.

### CODE REVIEW

**Comment by tammojan** [comment]
Has this branch been tested against the latest CASA?

**Comment by tammojan** [comment]
When merged, this fixes #134.

**Comment by tammojan** [comment]
@schiebel Could you merge this at an appropriate time?

**Comment by dmehring** [comment]
Contrary to the claim, these changes have broken our CASA build. I'm looking into that now...

**Comment by dmehring** [comment]
Looks like it was an issue with updating my sandbox with this change. If I do a complete rebuild, things work. Apologies for the false alarm

**Comment by gervandiepen** [comment]
Glad it was a false alarm. Darrell had built CASA successfully before this
change was committed.

**Pull request merged**
