### PR TITLE
Exceptions thrown in destructors of MS classes

### PR DESCRIPTION
**Pull request by gervandiepen**
Fixes issue #194

### CODE REVIEW

**Comment by tammojan** [comment]
Probably you don't want to change the namespace back to casa.. And why comment the exceptions instead of deleting them?

**Comment by gervandiepen** [comment]
Good point. I'll change the namespace to casacore.
It is outcommented because Harm did so.

**Comment by HarmMunk** [comment]
Delete them. I just left them in so that you could see the change without going through the (limited) hassle of a compare.

**Comment by tammojan** [comment]
It's not really pretty to see the amount of code duplication here. But perhaps that can be fixed some other time. See issue #134. Otherwise the code seems fine, so merging.

**Pull request merged**
