### PR TITLE
3.0 preparations

### PR DESCRIPTION
**Pull request by gijzelaerr**

### CODE REVIEW

**Comment by tammojan** [comment]
There's also the branch [prepare-2.5](https://github.com/casacore/casacore/tree/prepare-2.5). Could you merge them?

**Comment by tammojan** [comment]
Commit messages do not conform to the guidelines, otherwise great.

**Comment by rtobar** [comment]
Oh, I was actually trying to follow the guidelines, and in general tend to write short commit "titles" with longer bodies for the bulk of the explanation. Would it be possible to know which one is breaking the guidelines to pay more attention next time?

**Comment by tammojan** [comment]
Discussed with @gervandiepen , ok to increase major version. This will have some implications on LofarStMan etc, I'll make a bug report somewhere someday.

**Comment by tammojan** [comment]
@rtobar Your commit messages are great, I was referring to the other ones in this PR (that's you @gijzelaerr ;)

**Comment by gijzelaerr** [comment]
just to annoy @tammojan I will not capitalise my commit messages until the day I die.

**Pull request merged**
