### PR TITLE
Handle VLBA/DiFX data without zero-padding correctly 

### PR DESCRIPTION
**Pull request by kettenis**
Correction of the autocorrelations in the lag domain can only be
done properly if the correlator has zero-padded the data.  Handle
the case where data has not been zero-padded and assume this is
the default as DiFX doesn't zero-pad.

The VLBA correlator indicates whether data has been zero-padded by
setting the ZERO_PAD keyword in the MODEL_COMPS table to a non-zero
value.  Use this to override the default of assuming no zero-padding
has been done.

### CODE REVIEW

**Comment by dpetry** [comment]
@kettenis , hi, looks good but somewhere there should be a comment saying what the possible values of zeropad are and what their meaning is since you used an int and not a bool.

**Comment by kettenis** [comment]
Thanks @dpetry, the ZERO_PAD keyword is defined in AIPS memo 114, which documents it as "Zero padding factor", with further text stating that
`The oversampling and zero padding "factors" are given by the OVERSAMP and ZERO PAD keywords; a value of 0 for these keywords implies no oversampling and no zero padding.`
The code really only cares about the value being 0 to detect the no zero padding case. I think adding the comment at the point where the keyword is read makes the most sense.

**Review by dpetry — CHANGES_REQUESTED** [review]
OK, as I said, a little comment somewhere saying that zeropad can be 0 (meaning no padding applied) and non-zero (e.g. typically 1?, meaning zero padding has been applied) should be added.

**Comment by kettenis** [comment]
Yes, just pushed a revision that does this.

**Pull request merged**
