### PR TITLE
Check against wcslib 5.14, which throws segfaults (fixes #384)

### LINKED ISSUE #384: WCSlib 5.14 doesn't work with casacore
Hi,

If I build casacore against wcslib 5.13, all tests succeeed. If I build it against 5.14 about 40 fail. According to the release notes 5.14 fixes a memory leak (not sure if casacore relies on this leak).

Here is a list of tests that fail:
	438 - dCoordinates (Failed)
	439 - dRemoveAxes (Failed)
	440 - dWorldMap (Failed)
	442 - tCoordinateSystem (Failed)
	443 - tCoordinateUtil (Failed)
	444 - tDirectionCoordinate (Failed)
	445 - tFrequencyAligner (Failed)
	446 - tGaussianConvert (Failed)
	451 - tSpectralCoordinate (Failed)
	455 - dImageInterface (Failed)
	456 - dImageStatistics (Failed)
	457 - dImageSummary (Failed)
	459 - tExtendImage (Failed)
	460 - tFITSErrorImage (Failed)
	461 - tFITSExtImage (Failed)
	462 - tFITSExtImageII (Failed)
	463 - tFITSImage (Failed)
	465 - tFITSQualityImage (Failed)
	467 - tImageAttrHandler (Failed)
	469 - tImageConcat (Failed)
	470 - tImageEmpty (Failed)
	471 - tImageExpr (Failed)
	472 - tImageExpr2Gram (Failed)
	473 - tImageExpr3Gram (Failed)
	476 - tImageInfo (Failed)
	477 - tImageRegrid (Failed)
	478 - tImageStatistics (Failed)
	480 - tImageUtilities (Failed)
	481 - tLELSpectralIndex (Failed)
	483 - tPagedImage (Failed)
	484 - tPagedImage2 (Failed)
	485 - tRebinImage (Failed)
	486 - tSubImage (Failed)
	487 - tTempImage (Failed)
	488 - tImageRegion (Failed)
	490 - tWCBox (Failed)
	491 - tWCEllipsoid (Failed)
	492 - tWCExtension (Failed)
	493 - tWCLELMask (Failed)
	494 - tWCUnion (Failed)

This all for release version 2.0.3 but we have seen the same effect in 2.1.0 yesterday.

### PR DESCRIPTION
**Pull request by tammojan**

### CODE REVIEW

**Comment by juliantaylor** [comment]
hm is this necessary? this prevents usage of wcslib 5.14 with the issue patched

**Comment by tammojan** [comment]
Hm, maybe a fatal error is a bit much. I changed it to a warning.

**Comment by juliantaylor** [comment]
thanks, while a warning will probably be overlooked by everyone but as 5.15 also introduces a uninitialized use somewhere else (reported to upstream) some distributions might opt to patch 5.14 instead of upgrade the full thing.

**Comment by juliantaylor** [comment]
this does still need a comment with a small explanation and github issue number

**Comment by tammojan** [comment]
Shall I just add this to the CMakeLists.txt?
`# WCSlib 5.14 throws segfaults with casacore, see issue #384`

**Comment by juliantaylor** [comment]
yes maybe even as the warning itself, I'd also use gh-384 to further clarify in which tracker the issue is.

the CMakeList is already full of historical cruft, without a comment in a few years no-one will remember (or too lazy to git blame) why this line was added and whether it can be removed.

**Comment by juliantaylor** [comment]
actually even better mention the test which segfaults, to give the user a mean to test if there actually is a problem.

**Comment by tammojan** [comment]
Updated.

**Comment by juliantaylor** [comment]
thanks

**Pull request merged**
