### PR TITLE
CAS-8642: Make fits reader more robust w.r.t. invalid binary tables

### PR DESCRIPTION
**Pull request by dpetry**
Improved code to intercept possible segfault.
Made BinaryTable check the HDU error status before proceeding
with reading the HDU.

### CODE REVIEW

**Comment by juliantaylor** [comment]
c++98 build failed, Bintable.cc is missing a `#include "fits/FITS/hdu.h"` (no clue why c++11 works)

**Comment by juliantaylor** [comment]
ah my bad, it actually needs to be:

    HeaderDataUnit::OK

This is what changed in in c++11, there `HeaderDataUnit::HDUErrs::OK` is allowed

I guess the include can be kept as it is used directly

**Comment by juliantaylor** [comment]
urg please rebase before merging this mess in future

**Comment by juliantaylor** [comment]
I'm actually going to reset this, I have no idea what you even merged

**Comment by dpetry** [comment]
This change was just a few bytes. How can it be "a mess"?
Could we maybe discuss this in person?

**Comment by juliantaylor** [comment]
just look at the difference, 1500 lines changed and 13 commits to change a few bytes?
you have mixed in lots of different prs into this branch somehow

**Comment by dpetry** [comment]
Sorry. No idea how this happened. It was certainly not intentional.
I was just following git instructions.
If you can repair this, please do.

**Comment by dpetry** [comment]
Well, please let me know what you are going to do and if I still need to do anything.
Also, can I delete this branch now or do you need it?

**Comment by dpetry** [comment]
This may be a mess, but the final outcome seems to be the right one.
I just did an update on the NRAO svn copy of casacore and my changes are the only
ones which came through. The other 1500 lines did not.
So at least nothing was actually damaged.

I think what I probably inadvertently did is to recommit a number of already tested and merged pull-requests. So the final outcome was correct. It was just not exactly elegant.

Julian, I tried to contact you by phone to discuss this but didn't reach you.
Please confirm if all is fine from your point of view.

**Comment by tammojan** [comment]
If @juliantaylor has time, I actually prefer him to redo this merge. The commit history on the master should not have commits like "Darn: misread Julian's comment.". It shouldn't be too hard to redo this merge. @juliantaylor , are you still around?

**Comment by juliantaylor** [comment]
I am a bit concerned what happens with the svn export when one resets the branch.
The cli interface log does look reasonable, the criss cross merges just seem to confuse the github gui.

Its probably best to leave it as is now.

**Comment by tammojan** [comment]
Ok, if the only remaining problem is the wording of some commits on master, I can live with that.

**Comment by dpetry** [comment]
If the problem is really only the "Darn", I apologize. It was meant as an entertainment for you.
Sorry if it came across differently.
Anyway, I learned something today and will make sure this kind of merging problem
doesn't happen again. And in casacore comments, I will just say clean, simple sentences which cannot be misunderstood.

**Comment by tammojan** [comment]
Nothing wrong with entertainment of course! It's just that this type of commits should be squashed together to make one neat commit on the master branch.

**Pull request merged**
