### PR TITLE
Fix macOS CI

### PR DESCRIPTION
**Pull request by d3v-null**
runs tests on macos-13 (x68) and macos-14 (arm64)

I needed to pin boost to 1.83 because of this issue https://github.com/casacore/casacore/issues/1348 

Tests pass on macos-13, but two fail on macos-14 due to what appears to be floating point discrepancies

```txt
99% tests passed, 2 tests failed out of 493
Total Test time (real) =  79.27 sec
The following tests FAILED:
	226 - tLSQaips (Failed)
	227 - tLSQFit (Failed)


226/493 Test #226: tLSQaips .........................***Failed    0.07 sec
User time: 0
User time: 0
User time: 0
User time: 0
User time: 0
User time: 0
20,26c20,26
< Sol0: 1, 0.00582354, 0.00582354
< Sol1: 2, 0.00582354, 0.00582354
< Sol2: 0, 0.00582354, 0.00582354
< Sol3: 0, 0.00582354, 0.00582354
< Sol4: 0, 0.00582354, 0.00582354
< Sol5: 0, 0.00582354, 0.00582354
< Errors: 0.00151818, 0, 0, 0, 0, 0
---
> Sol0: 1, 0, 0
> Sol1: 2, 0, 0
> Sol2: 0, 0, 0
> Sol3: 0, 0, 0
> Sol4: 0, 0, 0
> Sol5: 0, 0, 0
> Errors: 0, 0, 0, 0, 0, 0
62,67c62,67
< Sol0: 1, 0.00582354, 0.00582354
< Sol1: 2, 0.00582354, 0.00582354
< Sol2: 0, 0.00582354, 0.00582354
< Sol3: 0, 0.00582354, 0.00582354
< Sol4: 0, 0.00582354, 0.00582354
< Sol5: 0, 0.00582354, 0.00582354
---
> Sol0: 1, 0, 0
> Sol1: 2, 0, 0
> Sol2: 0, 0, 0
> Sol3: 0, 0, 0
> Sol4: 0, 0, 0
> Sol5: 0, 0, 0
70,75c70,75
< Sol0: 1, 0.00582354, 0.00582354
< Sol1: 2, 0.00582354, 0.00582354
< Sol2: 0, 0.00582354, 0.00582354
< Sol3: 0, 0.00582354, 0.00582354
< Sol4: 0, 0.00582354, 0.00582354
< Sol5: 0, 0.00582354, 0.00582354
---
> Sol0: 1, 0, 0
> Sol1: 2, 0, 0
> Sol2: 0, 0, 0
> Sol3: 0, 0, 0
> Sol4: 0, 0, 0
> Sol5: 0, 0, 0
133c133
< mu: 0.00582354, me: 0.00582354
---
> mu: 0, me: 0
143c143
< mu: 0.00582354, me: 0.00582354
---
> mu: 0, me: 0
302c302
< mu: 1.94668e-07, me: 1.01662e-07
---
> mu: 0, me: 0
/Users/runner/work/casacore/casacore/build-tools/casacore_floatcheck:44: SyntaxWarning: invalid escape sequence '\g'
  line = regexp.sub (' \g<grp> ', line)
/Users/runner/work/casacore/casacore/build-tools/casacore_floatcheck:68: SyntaxWarning: invalid escape sequence '\.'
  numre = re.compile ('(?P<grp>[+-]?([0-9]+\.[0-9]*|[0-9]*\.[0-9]+|[0-9]+)([ed][+-][0-9]+)?)', re.IGNORECASE)
FAIL (floating point discrepancies > 1e-5): ./tLSQaips

        Start 227: tLSQFit
227/493 Test #227: tLSQFit ..........................***Failed    0.07 sec
User time:  0
User time: 0
User time: 0
User time: 0
User time: 0
User time: 0
20,26c20,26
< Sol0: 1, 0.00582354, 0.00582354
< Sol1: 2, 0.00582354, 0.00582354
< Sol2: 0, 0.00582354, 0.00582354
< Sol3: 0, 0.00582354, 0.00582354
< Sol4: 0, 0.00582354, 0.00582354
< Sol5: 0, 0.00582354, 0.00582354
< Errors: 0.00151818, 0, 0, 0, 0, 0
---
> Sol0: 1, 0, 0
> Sol1: 2, 0, 0
> Sol2: 0, 0, 0
> Sol3: 0, 0, 0
> Sol4: 0, 0, 0
> Sol5: 0, 0, 0
> Errors: 0, 0, 0, 0, 0, 0
158,163c158,163
< Sol0: 1, 0.00582354, 0.00582354
< Sol1: 2, 0.00582354, 0.00582354
< Sol2: 0, 0.00582354, 0.00582354
< Sol3: 0, 0.00582354, 0.00582354
< Sol4: 0, 0.00582354, 0.00582354
< Sol5: 0, 0.00582354, 0.00582354
---
> Sol0: 1, 0, 0
> Sol1: 2, 0, 0
> Sol2: 0, 0, 0
> Sol3: 0, 0, 0
> Sol4: 0, 0, 0
> Sol5: 0, 0, 0
166,171c166,171
< Sol0: 1, 0.00582354, 0.00582354
< Sol1: 2, 0.00582354, 0.00582354
< Sol2: 0, 0.00582354, 0.00582354
< Sol3: 0, 0.00582354, 0.00582354
< Sol4: 0, 0.00582354, 0.00582354
< Sol5: 0, 0.00582354, 0.00582354
---
> Sol0: 1, 0, 0
> Sol1: 2, 0, 0
> Sol2: 0, 0, 0
> Sol3: 0, 0, 0
> Sol4: 0, 0, 0
> Sol5: 0, 0, 0
234c234
< mu: 0.00582354, me: 0.00582354
---
> mu: 0, me: 0
244c244
< mu: 0.00582354, me: 0.00582354
---
> mu: 0, me: 0
403c403
< mu: 1.94668e-07, me: 1.01662e-07
---
> mu: 0, me: 0
/Users/runner/work/casacore/casacore/build-tools/casacore_floatcheck:44: SyntaxWarning: invalid escape sequence '\g'
  line = regexp.sub (' \g<grp> ', line)
/Users/runner/work/casacore/casacore/build-tools/casacore_floatcheck:68: SyntaxWarning: invalid escape sequence '\.'
  numre = re.compile ('(?P<grp>[+-]?([0-9]+\.[0-9]*|[0-9]*\.[0-9]+|[0-9]+)([ed][+-][0-9]+)?)', re.IGNORECASE)
FAIL (floating point discrepancies > 1e-5): ./tLSQFit
```

### CODE REVIEW

**Comment by tammojan** [comment]
Could you rebase on the latest master and try if that solve the issue with brew's boost?

**Comment by d3v-null** [comment]
Thanks for the quick fix @tammojan , that certainly simplifies the CI a bit. https://github.com/casacore/casacore/issues/1348

**Comment by tammojan** [comment]
I don't think the failing test is a simple floating point error,  at least it's further from zero than 1e-5 which is the default tolerance. However, I think having a working macos build is more important than fixing the last test on the latest platform. Could you disable the two remaining tests on MacOS 14?

One other thing: it's a bit curious that the test `tConvert` does not run in the CI jobs, even though you removed `-E tConvert`. Do you see why this happens?

**Comment by d3v-null** [comment]
Thanks @tammojan , I'll do that now. I'll create a new issue for the tests failing on arm64 to reference in the comments.

I'm not sure why the tConvert test doesn't run, but it could be because it's part of the python test suite, not the python3 test suite, and we're only building python3.

**Review by tammojan — APPROVED** [review]
Thank you!

**Pull request merged**
