### PR TITLE
Missed casa merges

### PR DESCRIPTION
**Pull request by JimNrao**
These are some relatively old mods that apparently missed the last major merge for CASA's casacore to the googlecode one.  The CASA version of the files appeared to be more recent than the corresponding one in github.

### CODE REVIEW

**Comment by tammojan** [comment]
It seems you forgot to add some files necessary for the test:
```
CMake Error: File /home/travis/build/casacore/casacore/images/Images/test/decon_test.im/logtable/table.info does not exist.
CMake Error at images/Images/test/CMakeLists.txt:32 (configure_file):
  configure_file Problem configuring file
```

**Comment by JimNrao** [comment]
Something looks fishy about the last commit.  I was trying to clean it up  and squash it down to a single commit, but it looks like other stuff might have got dragged in.  Maybe I should delete the PR and redo it cleanly?

**Comment by tammojan** [comment]
Looks fishy to me to. Do you remember what you did? Trying a new pull request sounds like a good idea (although probably there's a more git-like solution, like undoing some commit, reading, I don't know).

**Comment by JimNrao** [comment]
Something is wrong so I've reissued a newer, cleaner PR to accomplish this task without inflicting a messy (or worse) history onto the master.

**Pull request closed without merging**
