### PR TITLE
Array align init2

### PR DESCRIPTION
**Pull request by ithubg**
This is the enhancements for casa::Array to handle aligned memory and to skip unnecessary initialization.
It would  be nice if you could merge this pull request as soon as possible.

### CODE REVIEW

**Comment by ithubg** [comment]
Could someone restart the Travis CI builds above for OS X?
They failed before starting casacore build due to timeout of 3rd party library installation.

**Comment by tammojan** [comment]
I'm not sure a restart will do the trick, the master is failing for the same reason. I'll try to restart however.

**Comment by ithubg** [comment]
Thanks so much, Tammo.

**Comment by tammojan** [comment]
Travis is having some issues with the OSX builds. The linux builds seem to be fine.

@gervandiepen : could you review this change?

**Comment by ithubg** [comment]
Hi Ger,
Because this pull request need to be merged to master before CASA4.5 feature freeze, it would be nice if  you could review and merge it by July 29th.

**Comment by ithubg** [comment]
OS X builds failed with the following message this time.
The job exceeded the maxmimum time limit for jobs, and has been terminated.

**Comment by tammojan** [comment]
Travis is having issues with OSX now, so I'm afraid we cannot test on osx. Have you tested this PR yourself on OSX?

**Comment by ithubg** [comment]
I'm afraid I have not tested on OS X.

**Comment by gervandiepen** [comment]
Why has NAOJ been added to the copyright section? It has never been done for ASTRON, ATNF, ESO, etc.

**Comment by ithubg** [comment]
Because there is a possibility to reuse some part of the code in other NAOJ products, we want to preserve the copyright for the code.
Of course, we agree that the code is used and distributed under the license of casacore.

**Comment by gervandiepen** [comment]
I've done the merge.
Array is getting quite complex. Maybe we need a (short) note in casacore-notes describing the Array class and its allocator policies.
Maybe the changes have an effect on compilation time which has increased. For C++11 we could preinstantiate Array and Vector for the commmonly used types (e.g. the column types in tables). In this way they do not need to be instantiated in each compilation unit. Could you try this out?

**Comment by ithubg** [comment]
Thanks Ger.

The description for developers are available below.

https://safe.nrao.edu/wiki/bin/view/Software/CASA/TipsToOptimizeCppCodes#CASA_Specific_Tips

Yes for the preinstantiation.
Are Bool, Int, Float, Double, Complex, DComplex, String, MEpoch, MPosition and MDirection enough for "extern template"?

**Pull request merged**
