### PR TITLE
Remove update measures (#854)

### PR DESCRIPTION
**Pull request by gijzelaerr**

### CODE REVIEW

**Comment by tammojan** [comment]
I agree this script is so outdated and apparently unused that it can be removed.

**Comment by dpetry** [comment]
Just for my better understanding: wasn't this script necessary to perform the update of the measures tables at ASTRON? I vaguely remember that Gijs was working on fixing the one problem it had.

**Comment by gijzelaerr** [comment]
I think you are confused with the work @sabourke did to fix `measuresdata`. That one correctly updates the measures data, I assume this is an old, broken and deprecated script that did something similar.

**Comment by tammojan** [comment]
> Just for my better understanding: wasn't this script necessary to perform the update of the measures tables at ASTRON? I vaguely remember that Gijs was working on fixing the one problem it had.

Indeed, the now removed script only was to download measures data from ASTRON (probably similar to the cron job you have running). To create updated measures data, ASTRON uses the script `measuresdata.csh`, which is still there.

**Comment by dpetry** [comment]
Excellent. Thanks.

**Pull request merged**
