### PR TITLE
Added StorageOption argument to Table::copy

### LINKED ISSUE #374: Let Table::copy have an optional StorageOption argument
The copy and deepCopy function in class Table should have a StorageOption argument to make changing the storage format possible.

### PR DESCRIPTION
**Pull request by gervandiepen**
Copying an table can use the StorageOption argument.
showKeywords has been moved to class Table to be commonly available.
Close #374

### CODE REVIEW

**Comment by juliantaylor** [comment]
note that this change breaks binary compatiblity

**Comment by gervandiepen** [comment]
Changes in the BaseTable, etc. API/ABI are internal, thus do not break compatibility.
I do agree that addition of a parameter to the TableCopy copy function breaks the ABI. However, a few more non ABI-compatible changes have been checked in these days.
It is the intention that these changes (with the upcoming TaQL changes) become a next major release.

**Comment by juliantaylor** [comment]
its an installed header and a public function.
but its just an observation I think abi compatibility is not a worthwhile goal for something like casacore, but so far I know casacore is binary packaged in some places so it needs to at least be noted.

**Comment by gervandiepen** [comment]
Maybe we should add an issue to go through the CMakeLists files and only install the necessary header files.

**Comment by juliantaylor** [comment]
I guess the basetable header is needed at least a casa components includes it (but probably unnecessarily)
one could make it non-inheritable and make the public functions protected

**Pull request merged**
