### PR TITLE
Add support for importing FITS-IDI GAIN_CURVE tables

### PR DESCRIPTION
**Pull request by kettenis**
See issue #1039

### CODE REVIEW

**Comment by dpetry** [comment]
Did you look at the implications of adding this table to the MS for CASA tasks like mstransform and concat?

Also, comparing with the MS FEED table (which seems to be using the same key structure), you are using a TIME_RANGE while the FEED table uses TIME and INTERVAL. Maybe you should align you design with that of MS FEED and also mark the fields which form the key like in the MS Definition document.

If the structure of the key would be the same as for the FEED table, it would have the additional advantage that the reindexing code etc. in mstransform and concat could be re-used. 

(I'm going to add this comment also to the Issue.)

**Comment by dpetry** [comment]
OK, I'm going to merge this now.
But NOTE that the CASA importfitsidi task uses ms.concatenate() if the input is a list of FITSIDI files!
So the next step will have to be to make sure that concat handles the new GAIN_CURVE tables properly.

**Comment by dpetry** [comment]
@kettenis and @aroffringa , there are reports of compilation problems related to this PR from CASA developers.
@kettenis, could you try and compile the latest CASA Master with a casacore version which contains this PR.

**Comment by kettenis** [comment]
I can confirm that CASA doesn't build against the current casacore master.  This is obviously related to #1029 since the problem is with code in CASA that still uses FFTPACK through the FFTPack class. I guess the problem is that the change I tested for @aroffringa didn't actually remove the FFTPack code from casacore yet, whereas the final PR did.

I think the easiest way out of this mess is to reinstate the FFTPack class and the FFTPACK Fortran code in casacore (but keep the changes to make FFTServer and the FITS-IDI conversion code to use FFTW unconditionally). Compilation of the FFTPACK code should probably be conditional such that other casacore users that wish to use modern compilers can do so.

Long-term, the code in CASA should probably be converted to use FFTW by the corresponding code owners as FFTPACK is no longer maintained and can't be compiled by GCC 10.

**Comment by tammojan** [comment]
Since André is on vacation, I can pick this up. I hope Wednesday is early enough. Mark, can you point me to instructions on compiling casa?

**Comment by cquike** [comment]
Hi,
thank you for looking at this! Indeed, the problem is in #1029 rather than here. I just discovered when using the tip of master. The proposal from @kettenis sounds quite good: make FFTPack optional so that different applications can decide. Eventually CASA might also move away from FFTPack, but that will obviously require quite some time and we are not there yet.

**Comment by cquike** [comment]
Curiously enough the commit that removed FFTPack (https://github.com/casacore/casacore/commit/33c8d5f8468860239800ab1592cd4636a80108e7) is not part of #1029 ... Was yet another PR that was dealing with this?

**Comment by kettenis** [comment]
Ah, that explains why I didn't see this when I initially tested the changes proposed by @aroffringa. That commit is part of PR #1024 which references issue #1017. I think that is exactly the commit that needs to be reverted and then made conditional using some cmake magic.

@tammojan it is probably easiest for me to provide you with an account on our casa development machine at JIVE if you want to take this on (my ability to do cmake magic is fairly limited).

**Pull request merged**
