### PR TITLE
cache travis compile result with ccache

### PR DESCRIPTION
**Pull request by juliantaylor**
hopefully speeds up the builds a bit

### CODE REVIEW

**Comment by juliantaylor** [comment]
don't merge yet, still testing

**Comment by juliantaylor** [comment]
sweet it works :D
50 minutes down to 5

**Comment by juliantaylor** [comment]
mac still needs checking, probably tomorrow.

**Comment by tammojan** [comment]
Nice!!

**Comment by juliantaylor** [comment]
too bad travis assumes ccache is not available on mac so it doesn't upload the cache, but doing it manually via directory should work

**Comment by juliantaylor** [comment]
or cache doesn't work on mac at all :(
seems to be only available on containers for free
So this should be read to merge then. It does give fast feedback for linux at least

**Comment by juliantaylor** [comment]
lets give this a field test.

**Comment by juliantaylor** [comment]
neat osx caching should now be free too, lets see if the current settings work
https://blog.travis-ci.com/2016-05-03-caches-are-coming-to-everyone

**Pull request merged**
