### PR TITLE
Issue #56 Remove all obsolete files and directories

### PR DESCRIPTION
**Pull request by gervandiepen**
Removed all obsolete files and directories

### CODE REVIEW

**Comment by juliantaylor** [comment]
this probably shouldn't remove install/COPYING
isntead casa/test/COPYING could be removed as that its location does not imply its valid for the full sourcve

**Comment by gervandiepen** [comment]
You might be right. I'll check.

**Comment by gervandiepen** [comment]
Maybe better to move COPYING to the casacore directory. What do you think?

**Comment by juliantaylor** [comment]
thats probably better, the top level directory is usually the place you find the license

**Comment by tammojan** [comment]
Rebased this on top of the current master, so checks will run with proper travis settings.

**Comment by tammojan** [comment]
@juliantaylor Could you merge this?

**Pull request merged**
