### PR TITLE
Fix support for newer cmake boost issue #844

### PR DESCRIPTION
**Pull request by gijzelaerr**

### CODE REVIEW

**Comment by gervandiepen** [comment]
All builds failed.

**Comment by gijzelaerr** [comment]
see https://github.com/casacore/casacore/issues/847

**Comment by tammojan** [comment]
If there's an easy way to make this work also in ubuntu 16 (perhaps involving a command-line override for the boost-python library name), that would be helpful. We cannot assume everyone has switched to ubuntu 18.

**Comment by gijzelaerr** [comment]
there you go

**Pull request merged**
