### PR TITLE
Added methods to ImageProxy to return objects

### PR DESCRIPTION
**Pull request by dmehring**
Added imageInfoObject() and type() methods to return native casacore objects/types rather than Records/Strings.

### CODE REVIEW

**Comment by dmehring** [comment]
@gervandiepen ImageProxy mods, as we discussed.

**Comment by gervandiepen** [comment]
Nice.
I only wonder why you return ImageInfo by value and not by const ref. By value is more expensive.

You could add a similar function for the CoordinateSystem.

**Comment by dmehring** [comment]
True, const ref would be better.

**Comment by dmehring** [comment]
@gervandiepen Modified so imageInfoObject() returns const ref, added coordSysObject() which also returns const ref.

**Pull request merged**
