### PR TITLE
Added code to properly copy also the SIGMA_SPECTRUM column in the Main…

### PR DESCRIPTION
**Pull request by dpetry**
… table in MSConcat.cc, CAS-10221
This is very localised and was tested to not break any casacore unit tests.
It was also tested to work within the NRAO CASA 5.1 build.

### CODE REVIEW

**Comment by tammojan** [comment]
Looks good. In the future, could you format your commit message in 70 characters (when necessary append two newlines and however many extra text).

**Comment by dpetry** [comment]
Thanks! OK, will try to remember the formatting.

**Comment by mpokorny** [comment]
@tammojan since I'm now approving pull requests, should I encourage commit authors to limit commit messages to 70 characters? I'm all for it, personally.

**Comment by tammojan** [comment]
> @tammojan since I'm now approving pull requests, should I encourage commit authors to limit commit messages to 70 characters?

Yes please. We should try to follow the commonly accepted standards where possible.

**Pull request merged**
