### PR TITLE
Cas 11100 implement biweight stats algorithm and add support to LattStats for it

### PR DESCRIPTION
**Pull request by dmehring**
Also, make various stats framework methods virtual that should be virtual
change npts type from Int64 to uInt64 in a bunch of places
Add comprehensive unit tests for new BiweightStatistics class
Add unit tests to tLatticeStatistics to verify biweight algorithm works as expected there

### CODE REVIEW

**Comment by dmehring** [comment]
The CI failure appears to be due to a timeout; ie something beyond my control:

"The job exceeded the maximum time limit for jobs, and has been terminated."

**Comment by dmehring** [comment]
Just a note that this is a high priority item for the CASA project. It is related to n-sigma clean.

**Comment by mpokorny** [comment]
It looks like the failures in the non-c++11 builds are back. I can't _see_ any problems in your PR that would be responsible, so I think blaming the failure on the build system is reasonable.
That's a lot of changes! But it looks as if you have sufficient unit tests -- enough for me to proceed with the merge.

**Comment by dmehring** [comment]
Thanks for the quick review Martin.

**Pull request merged**
