### PR TITLE
Added MPI support for parallel CTDS I/O

### PR DESCRIPTION
**Pull request by JasonRuonanWang**
See discussions in #729 

This PR added MPI support for the casacore table data system. Previously we can partially achieve parallel I/O by introducing a parallel storage manager (e.g. https://github.com/SKA-ScienceDataProcessor/AdiosStMan). However, the table layer API was strictly serial for writing. In this PR, I added MPI-awareness to the table layer API. The logic is to write the table files only on Rank 0, while other ranks do not write any data. This fixed the issue that slave ranks of user applications have to pass in garbage tables with the table API to avoid conflicts when writing table files. 

To use this feature, one must configure casacore using the following flags

-DUSE_MPI=ON 
-DENABLE_TABLELOCKING=OFF

Also, one must use a parallel CTDS storage manager. Some of the existing parallel storage managers are:
https://github.com/SKA-ScienceDataProcessor/AdiosStMan
https://github.com/JasonRuonanWang/Adios2StMan
https://github.com/JasonRuonanWang/Hdf5StMan

### CODE REVIEW

**Comment by gervandiepen** [comment]
Hi Jason,
It looks nice. It's smart that you use openedForWrite() to not write the meta info for MPI ranks > 0.
I assume you have tested it with the Adios2StMan. Did you get good results?
The only thing you possibly could improve on is that the code in the BaseTable and PlainTable constructors you cloned is put in a single shared function.
Cheers, Ger

**Comment by JasonRuonanWang** [comment]
@gervandiepen Yes sir! I have put the common code for the constructor in a BaseTableCommon() and PlainTableCommon() and call them from the MPI and non-MPI constructors respectively. The reason why I didn't do this is because I wasn't sure if I need to change the procedures in those. But since I found the openedForWrite() trick I believe I probably won't need to touch the constructors any more.

I am still working on Adios2StMan, but I have tested it using AdiosStMan and Hdf5StMan. Everything is working as expected, which is not surprising because this table layer change does not affecting how parallel storage managers work. It just provides a nicer way to write parallel applications and makes them fully compatible with serial applications. I will let you know once I finish Adios2StMan and the performance testing.

**Comment by gervandiepen** [comment]
Great work sir! I'll take a look at your new StMans.
I have still one question left. How did you solve the addRow problem which
(in principle) has to be done before you can write a new row? Is it ignored
in the parallel StMans?

Do you have any idea how much overhead the table system causes compared to
raw Adios or HDF5?

**Comment by JasonRuonanWang** [comment]
@gervandiepen I haven't pushed Adios2StMan to the repo yet but it wont't take too long time. 

For addRow what I did previously in AdiosStMan is to disable that. But if it's a requirement then it shouldn't be hard to enable it in Adios2StMan. All this kind of table operations, I will only do it on Rank 0, since that's the rank which actually holds the table metadata. So from the user application's perspective, it can either call addRow on Rank 0 or call it on all ranks, which won't make difference. 

But from what I understand most of the use cases including MeasurementSets, it's not difficult to determine a total number of rows beforehand. So I wouldn't encourage applications to change table properties frequently which for sure will harm the performance. 

For the overhead issue, I haven't compared between the CTDS table system and ADIOS/HDF5, because for everything I have done, table metadata is still stored in CTDS/AipsIO. But if you mean the column level, then if I remember ADIOS1 takes a little more overhead than the standard storage manager. I think it's because it needs to manage the meta data information for every rank.

**Comment by mpokorny** [comment]
I confess to not thinking too much about the details of whether this code would be sufficient to support the work I've been doing, but it does address the first major design issue in the table system code that I encountered. These changes are certainly necessary for what I'd like to do, and the implementation looks fine.

**Comment by JasonRuonanWang** [comment]
@mpokorny Thanks for the follow-up. I believe this is the base functionality that any parallel CTDS IO is likely to need. In the meantime we can certainly keep discussing what are the common things we will need for the next step.

**Comment by tammojan** [comment]
Merging this; future extensions can go into a new PR.

**Comment by tammojan** [comment]
Thanks for the great work so far, @JasonRuonanWang !

**Pull request merged**
