### PR TITLE
CAS-10933 reorg of stats framework code

### PR DESCRIPTION
**Pull request by dmehring**
This is a reorganization only. There are no functionality changes.
Move stats framework code to scimath/StatsFramework, in anticipation of a significant refactor that will result in the creation of new stats framework classes.
Because the timescale of the refactor is somewhat uncertain and development may continue over an extended time period, and because other unrelated stats framework issues may occur in the interim which require changes to this code, it is preferred to reorg now rather than later to mitigate any possible future merge complexities.
The new directory name is preferred to a more generic name, eg "Statistics", because there are older statistics related classes still in scimath/Mathematics that are not part of the new statistics framework.
symlinks in scimath/Mathematics which point to the relevant .h files in scimath/StatsFramework have been created so include paths that other packages use will not break.

### CODE REVIEW

**Comment by gervandiepen** [comment]
I think the symlinks should be removed once CASA uses the new include paths. AFAIK the source files are not used at other places.
Will Martin do the merge?

**Comment by dmehring** [comment]
No problem. that can all be done as part of the same casa branch, so I can just remove the symlinks now which was my plan anyway. I just didn't want to trip up anyone outside the casa team.

**Comment by mpokorny** [comment]
I won't be in the office all week. I might get around to doing the merge, but it could take a while. I wouldn't mind if someone else got to it before me.MartinOn Nov 20, 2017 07:40, dmehring <notifications@github.com> wrote:No problem. that can all be done as part of the same casa branch, so I can just remove the symlinks now which was my plan anyway. I just didn't want to trip up anyone outside the casa team.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/casacore/casacore","title":"casacore/casacore","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/casacore/casacore"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dmehring in #663: No problem. that can all be done as part of the same casa branch, so I can just remove the symlinks now which was my plan anyway. I just didn't want to trip up anyone outside the casa team."}],"action":{"name":"View Pull Request","url":"https://github.com/casacore/casacore/pull/663#issuecomment-345714796"}}}</!
 MailScannerScript24528>

**Comment by dmehring** [comment]
@gervandiepen I've removed the symlinks. Since @mpokorny is unavailable for awhile, would you be able to do this merge? I suspect it is straight forward.
Thanks

**Pull request merged**
