### PR TITLE
Style changes, indentation, brackets, loop counter postfix -> prefix

### PR DESCRIPTION
**Pull request by dmehring**
Implementation changes to follow.

### CODE REVIEW

**Comment by dmehring** [comment]
@juliantaylor If I make a pull request and then push more changes to the same file on the same branch before the first pull request is merged, is the reviewer able to see both my changes individually, or are they only able to see the union of both changes? I ask because this first change is style only, and the next change involves implementation changes, so it would be easier for the reviewer  to review them individually. If the reviewer is unable to distinguish between the two, I will hold off on my next push until the first has been merged.

**Comment by juliantaylor** [comment]
if you just add commits they can be reviewed separately, its a bit less convenient but not a problem
make the added commits as self contained as reasonable.

**Comment by dmehring** [comment]
OK thanks. So just committing separately is OK? I don't have to push them each time and so can push a set of multiple commits in one go and that will be OK to review?

**Comment by juliantaylor** [comment]
yes you can push a set of commits in one go, but try to be descriptive in the commit messages.

**Comment by gervandiepen** [comment]
I don't agree with the style changes in existing source files.
The code in Casacore had this style for a very long time, and it makes no sense to change it. We agreed that existing style would not be changed.

**Comment by dmehring** [comment]
Hi Ger
Do you object to all changes or just some? 

In the case of the indentation changes, the header file uses spaces for indents but the .cc file uses tabs.  It takes unnecessary time to reconfigure ones editor when switching between the two files. 

Prefix ++ is more efficient than postfix ++ for simple incrementing of counters.

**Comment by gervandiepen** [comment]
I don't object to replacing tabs by spaces and using prefix instead of
postfix (it is indeed better in a loop). I also do that in a regular way.
But you also change the placement of braces, the way function signatures
are written, constructor initializition is done, etc.
We all have our favourite style and our opinion about what is most
readable. It is fine for new code. But IMHO existing code should not be
changed like that.

**Comment by dmehring** [comment]
So if I revert the changes in bracket placement, method signatures, and constructor initialization, then you'd be willing to accept the code? Anything else? 
Ultimately I'm adding code so this class will support creation of an ellipsoid with center outside the lattice, which is a required use case for our users. 
Thanks.

**Comment by dmehring** [comment]
@gervandiepen I've reverted my style changes to which you object. I hope this now meets with your approval. I've implemented support for the case when the ellipsoid center is outside the lattice. I've added tests. I've added a test fixture to which test results can be compared.
Thanks.

**Comment by gervandiepen** [comment]
Looks nice.
Ger

**Comment by dmehring** [comment]
Thanks!

**Pull request merged**
