### PR TITLE
Issue 970

### PR DESCRIPTION
**Pull request by bennahugo**
- fixes longstanding bug in incremental storage manager slice reading
 - clean up code duplication and simplifies getcolcells ~~static~~ preprocessor
definition
Incremental storage manager test ran successfully:
```
Start 200: tIncrementalStMan
200/530 Test #200: tIncrementalStMan ................   Passed    2.15 sec
```

### CODE REVIEW

**Comment by bennahugo** [comment]
Specifically this bit of code is missing a else case.
So the logic should flow something along the lines for each slice read values directly  with the getvalue call if the cache is invalid, otherwise read values **up** to the end of the cache
```
            while (rownr <= end) { \
                if (rownr < cache.start()  ||  rownr > cache.end()) { \
                    aips_name2(get,NM) (rownr, valptr); \
                    DebugAssert (cache.incr() == 0, AipsError); \
                } \
                const T* cacheValue = (const T*)(cache.dataPtr()); \
                uInt endrow = min (end, cache.end()); \
                while (rownr <= endrow) { \
	            *valptr++ = *cacheValue; \
                    rownr += incr; \
```
replaced with
```
                while (rownr <= end) {
                    if (rownr < cache.start()  ||  rownr > cache.end()) {
                        get<T>(rownr, valptr);
                        DebugAssert (cache.start() == 1, AipsError); // assert cache invalid
                        DebugAssert (cache.end() == 0, AipsError);
                        DebugAssert (cache.incr() == 0, AipsError);
                        rownr += incr;
                        valptr++;
                    } else { // cache not invalid, read up to the end of the cache
                        const T* cacheValue = (const T*)(cache.dataPtr());
                        uInt endrow = min (end, cache.end());
                        DebugAssert(cache.incr() == incr, AipsError);

                        while (rownr <= endrow) {
                            *valptr++ = *cacheValue;
                            rownr += incr;
                        } 
                    }
```

**Comment by bennahugo** [comment]
tagging @gervandiepen here. From the blame log it looks like you were the original author. Could you please review.

**Comment by sjperkins** [comment]
I'd like  to expand on @bennahugo 's analysis of the issue:

```cpp
while (rownr <= end) {
    // There are two cases handled by this if statement:
    //    (1) The cache doesn't contain the requested data
    //    (2) The cache is in an invalidated state (start=1, end=0, incr=0)

    // I think this logic handles (1) and (2) correctly
    if (rownr < cache.start()  ||  rownr > cache.end()) {
       // extract data from the storage manager
        aips_name2(get,NM) (rownr, valptr);
        // Assert cache is in invalidated state?
        DebugAssert (cache.incr() == 0, AipsError);
    }

    // This logic only handles (1) correctly.
    const T* cacheValue = (const T*)(cache.dataPtr());
    // The problem occurs here. If the cache was previously invalidated,
    // cache.end() == 0
    // which imples endRow == 0
    uInt endrow = min (end, cache.end());
    // which implies the following while loop never increments rownr
    while (rownr <= endrow) {
    *valptr++ = *cacheValue;
        rownr += incr;

    // which implies that the outer while loop starts again with the same rownr.
```

and the loop continues forever.

**Comment by sjperkins** [comment]
@tammojan @gervandiepen Is there anything else required from this PR?

**Comment by tammojan** [comment]
> I wonder why you want to make this change. Did you get some error somewhere?

@gervandiepen The issue is described in #970.

**Comment by sjperkins** [comment]
> I wonder why you want to make this change. Did you get some error somewhere?

There is an example that reproduces this for me in this comment: https://github.com/casacore/casacore/issues/970#issuecomment-544850460

We're encountering an infinite while loop in the above code. It occurs when the ColumnCache is in an invalidated state: `(start=1, end=0, incr=0)`:

https://github.com/casacore/casacore/blob/740f336cb9f343ce5a139585d8fe4a0d691df447/tables/Tables/ColumnCache.h#L129-L132

I feel that the problem with this case is sufficiently described in https://github.com/casacore/casacore/pull/971#issuecomment-545903279. Would you mind having another look at that? If that's not sufficient, I'll try again.

**Comment by tammojan** [comment]
This PR was superseded by #974, which fixes #970 in a more fundamental way.

**Pull request closed without merging**
