### PR TITLE
Fix JPL ephemerides download (DE200, DE405)

### PR DESCRIPTION
**Pull request by sabourke**
Fix for casacore/casacore/issues/537

### CODE REVIEW

**Comment by dpetry** [comment]
It is great that you took the time to work on this. Thanks!
Since the main site to run this is ASTRON, I leave it to somebody from there to approve this.
What tests did you perform?

**Comment by sabourke** [comment]
I tested them both from python with code similar to the sample in #799, compared the keywords and desc of the generated tables with the ones distributed in CASA<sup>1</sup> and examined them in the table browser. 

<sup>1</sup> some keywords in the CASA tables have a newline at the end which doesn't look intentional. It doesn't cause problems though. The tables generated by measuresdata in casacore don't have this issue.

**Comment by dpetry** [comment]
Which keywords have the additional newline?
Could this still be fixed?
(Might cause problems in the automated interpretation of the keywords.)

**Comment by gijzelaerr** [comment]
Awesome, I think this is important enough to get into the imminent 3.0 release, but I don't have the knowledge to verify this results in the correct data and this PR is correct. @tammojan @gervandiepen ?

**Comment by dpetry** [comment]
@tammojan , could this be tested in the ASTRON context ?

**Comment by sabourke** [comment]
@dpetry The issue is present in the tables distributed by NRAO, **not** the tables generated by casacore + this PR and it's not actually causing any problem. JDEPOC, MA0001 and QQQQQQ

**Comment by dpetry** [comment]
Yes, the NRAO tables are updated from the ASTRON master copy since some time.
So, from my point of view this could be merged but I would like @tammojan to comment or better test  this because he knows best (AFAIK) how this code is used to create the ASTRON distribution of CASA data.

**Comment by tammojan** [comment]
@gijzelaerr Could you run `measuresdata-update`  on this branch?

**Comment by gijzelaerr** [comment]
I can successfully run `measuresdata-update` on the casacore-data data, and it looks like `IERSeop2000`, `IERSeop97`, `IERSpredict`, `IERSpredict2000` and `TAI_UTC` get updated.

**Comment by sabourke** [comment]
@gijzelaerr which `measuresdata` is getting called by `measuresdata-update`? The one from this branch or is the standard old version in you PATH?

**Comment by gijzelaerr** [comment]
good point. that was the old `measuresdata`. If I remove my old measuredata and use the new one I get:

```
gijs@gijs-artica:/opt/casacore/data  
λ  PATH=/opt/casacore/bin:$PATH measuresdata-update
Calling measuresdata
 
Create data tables for Measures
-----------------------------------------------
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
Aborted (core dumped)
Severe error calling measuresdata with
```

**Comment by sabourke** [comment]
Aw man... ok, I'll look into this either today to Monday

**Comment by sabourke** [comment]
This looks like a regression in casacore. If you build the master branch it also crashes, right? @gijzelaerr can you confirm?

**Comment by gijzelaerr** [comment]
I can confirm this also happens with the current master. https://github.com/casacore/casacore/issues/814

**Comment by tammojan** [comment]
The astron server that updates the measures data is still on casacore 2.7 and will not be updated in 2018. While I think it is great to fix the measures update programs on master, this should not block the release of casacore 3.0.

**Comment by gijzelaerr** [comment]
ok, then we are good to go for 3.0. will do on Monday.

**Comment by gijzelaerr** [comment]
https://github.com/casacore/casacore/issues/815 has been resolved.

**Pull request merged**
