### PR TITLE
Cas 8525  Fix bug in which min/max pos strings were being determined if min/max pixel location was empty

### PR DESCRIPTION
**Pull request by dmehring**
Two commits:
1. Fix bug in which min/max pos strings were being determined if min/max pixel location was empty.
2. substitute spaces for tabs for indentation.

### CODE REVIEW

**Comment by juliantaylor** [comment]
`formatCoordinate` should also raise an error on mismatching input, this doesn't look like a function where one needs to skip boundary checks for performance

**Comment by dmehring** [comment]
Check added as requested, unit test added to verify it.

**Comment by juliantaylor** [comment]
excellent, thank you

**Comment by dmehring** [comment]
Thanks!

**Pull request merged**
