### PR TITLE
ADIOS2/MPI compilation fixes

### PR DESCRIPTION
**Pull request by rtobar**
This is a small set of changes around the compilation of casacore using `USE_ADIOS2=ON` (and therefore `USE_MPI=ON`). @JasonRuonanWang might be interested on these changes too.

After these changes I was able to compile the software. I still get a failure in {{tMSSelection}}, but I'd venture it's unrelated to these compilation fixes, and probably already present in the {{master}} branch with `USE_ADIOS2=ON` (but definitely not seen with `USE_ADIOS2=OFF`).

### CODE REVIEW

**Comment by JasonRuonanWang** [comment]
@rtobar Thanks for the fixes. I tried running tMSSelection, and I got a failure for the first time. But as soon as I ran the second time with a -VV to see what happened, it passed. From the second time on it always passes. Anyone knows what this could be?

**Comment by rtobar** [comment]
For the record, I tried running the test with valgrind, but nothing new came out of that. Re-running the test didn't make a difference for me.

@JasonRuonanWang, could you confirm whether you saw the failure in `tMSSelection` without the patches in this PR applied? That would at least help us confirm whether the failure was there before the patches, or if it was introduced with them.

**Comment by JasonRuonanWang** [comment]
These are the error messages I got 


test 399
    Start 399: tMSSelection

399: Test command: /Users/jason/casacore/cmake/cmake_assay "./tMSSelection"
399: Test timeout computed to be: 1500
399: 1,48c1,1744
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: < ###AipsError: Table DataManager error: Internal error: TiledStMan::headerFileGet: mismatch in #row; expected 0, found 1058
399: ---

**Comment by JasonRuonanWang** [comment]
I have checked the current master before merging these fixes. It still fails, but the errors seem to be from TiledStMan rather than Adios2StMan. 

One possible reason might be that this test relies on some of the output files of previous tests, and I might have touched some previous tests to incorporate Adios2StMan.

This is very hard to test since the tests are not enforced in the continuous integration before merging into master. So it's almost impossible to track all activities that might have changed the behavior of these tests. We probably have to work together with the author of this test to know what exactly these errors mean...

**Comment by rtobar** [comment]
Yes, those are the exact same errors I get.

**Comment by gervandiepen** [comment]
I've looked briefly into the tMSSelection problem and it looks as if is
related to TableNoLocking which is enforced by ADIOS2=ON. I'll continue the
investigation.

**Comment by JasonRuonanWang** [comment]
@gervandiepen Okay, that sounds more reasonable, because I don't remember I touched anything related to this test. Thanks for looking into this!

**Comment by gervandiepen** [comment]
Jason,
Do you agree with the changes Rodrigo made in the CMakeLists.txt files? If
so, I'll merge the PR.

I've found the cause of the tMSSelection failure and solved it. At the same
time I found a memory leak in AdiosStMan and fixed that. I'll create a PR
for it.

Ger

**Comment by JasonRuonanWang** [comment]
Yes, it looks good. Please go ahead.

**Pull request merged**
