### PR TITLE
Remove allocator Template parameter from Arrays

### PR DESCRIPTION
**Pull request by aroffringa**
This simplifies the Array code quite a lot, and probably (not tested) results in a compilation speed up. It also improves compiler error output when a parameter is in error.

Finally, although leaving the template allocator empty results in the default state-less std::allocator, which the compiler should be able to optimize away, in practice this wasn't true. The Array constructor in particular became quite a bit faster by removing the allocator.

### CODE REVIEW

**Comment by tammojan** [comment]
In case you missed it, CI says there's still an allocator template argument used in casa/IO/ArrayIO.h:101:
```
LogIO &operator<<(LogIO &os, const Array<T, Alloc> &a);
```

**Comment by aroffringa** [comment]
Maybe this is something for @gervandiepen to review?

**Comment by gervandiepen** [comment]
I'll do it next week.

**Comment by gervandiepen** [comment]
Looks like a good change.
It is not possible to allocate in shared memory anymore, but that is no problem because it can be done by allocating first and use the pointer to make the Array object. With the old Alloc parameter a shared memory Array would be resized in shared memory which would be very bad. That is not possible anymore.

**Review by gervandiepen — APPROVED** [review]

**Pull request merged**
