### PR TITLE
 	CAS-7309 add support to ImageOpener for componentlist images

### PR DESCRIPTION
**Pull request by dmehring**
Added COMPLISTIMAGE to ImageOpener::ImageTypes enum
Added logic to ImageOpener::imageType() for case when to return the new enum.
Added IPositionComparator class as part of IPosition files to allow std::map to be created using IPositions as keys. Added tests for that to tIPostion.cc

### CODE REVIEW

**Comment by dmehring** [comment]
It appears that this build failed because it exceeded the time limit? Would someone who understands how travis works please take a look?

**Comment by dmehring** [comment]
@tammojan @mpokorny can one of you help with this? It appears the build was proceeding fine but the time out was reached.
Thanks

**Comment by tammojan** [comment]
The clang build passes fine, the gcc build (or more relevantly the non-c++11 build) times out, as happened in most other PR's. This problem is known, I will try to look into it at the end of this week. I don't think the time-out should prevent this PR to be merged.

As comment on the actual PR: it looks fine to me. Although the merge commit should ideally be left out.

**Comment by dmehring** [comment]
I will submit a new PR that doesn't have the merge. Thanks.

**Pull request closed without merging**
