### PR TITLE
CASA uses a somewhat unique numbering scheme for it's shared librarie…

### PR DESCRIPTION
**Pull request by JimNrao**
…s. In this cmake file if the user sets CASA_BUILD=1 then the build logic will use CASA's numbering scheme; when that setting is not utilized, only the standard cmake logic will be invoked.

I'm making this pull request at the request of our build guy who's out of the country on an extended vacation (lucky bastard). The problem we have is that we build and semi-release lots of versions of the various shared libraries so we need a scheme to help manage them.

### CODE REVIEW

**Comment by JimNrao** [comment]
This is a cleaner (hopefully) version of the previous, messy PR to accomplish getting CASA to build.  However, it's always possible that it contains mistakes.

**Comment by tammojan** [comment]
@jimnrao : since this is all Casa specific (and is disabled by default), feel free to merge yourself after the Travis tests pass. 

A comment for next time: could you come up with a slightly more concise commit message?

**Comment by JimNrao** [comment]
Great.  We might later want to find a way to isolate the CASA-specific 
mods to the cmake file.  Maybe an optional external cmake module that 
just has a simple hook in the main.  However, that will have to wait 
until our build guy gets back.

Our local convention for SVN commits often involves making fairly 
detailed commit messages.  When someone is trying to look back through 
and understand a sequence of commits, what would they normally look at 
to learn the intent?

On 07/01/2015 02:51 PM, Tammo Jan Dijkema wrote:
>
> @jimnrao <https://github.com/jimnrao> : since this is all Casa 
> specific (and is disabled by default), feel free to merge yourself 
> after the Travis tests pass.
>
> A comment for next time: could you come up with a slightly more 
> concise commit message?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/casacore/casacore/pull/145#issuecomment-117820884>.Web 
> Bug from 
> https://github.com/notifications/beacon/AGPGtJmLI5Ki6Rowyhkis4u9T2uy0N0tks5oZEpugaJpZM4FQJ99.gif
>

-- 
Jim Jacobs

phone: 835-7235
office: 301

**Comment by juliantaylor** [comment]
I agree, the longer the commit message the better usually.
Note git commit message convention is 72 character header line, then empty line then 80 character wrapped long description. most tools (git send-email, or also github PR') use this structure for layout.

**Comment by JimNrao** [comment]
Thanks; that sounds like a better approach that will yield a readable 
title while having all of the details present.  The truncated version of 
my first sentence made a pretty odd title, hence Tammo's remark.  So 
many conventions to discover/learn on top of the git/github mechanics.

On 7/2/2015 1:26 AM, Julian Taylor wrote:
>
> I agree, the longer the commit message the better usually.
> Note git commit message convention is 72 character header line, then 
> empty line then 80 character wrapped long description. most tools (git 
> send-email, or also github PR') use this structure for layout.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/casacore/casacore/pull/145#issuecomment-117941239>.Web 
> Bug from 
> https://github.com/notifications/beacon/AGPGtHdw_RClADSh6dFezT_2BiYjbdXbks5oZN83gaJpZM4FQJ99.gif
>


-- 
Jim Jacobs

**Pull request merged**
