### PR TITLE
Do not convert a normal exception

### PR DESCRIPTION
**Pull request by gervandiepen**
Issue #243
Added exceptions to tests

### CODE REVIEW

**Comment by juliantaylor** [comment]
the three commits could be squashed

**Comment by juliantaylor** [comment]
it would also be better when you stopped using the main repo for your branches or at least delete the old stuff, the main repository is full up with lots of junk branches.

**Comment by gervandiepen** [comment]
I thought the revert would completely undo the commit, but I found out too
late that it results in a separate commit.

**Comment by juliantaylor** [comment]
its never to late with git, just do git rebase -i HEAD^^^ and squash it

**Pull request merged**
