### PR TITLE
CAS-11049 accounting-specific methods/fields 

### PR DESCRIPTION
**Pull request by dmehring**
…taset

from ClassicalStatistics to StatisticsDataset
Also, bundle data chunk-specific fields into a single struct and reduce number of necessary fields by using PtrHolders to indicate if mask, weights, and ranges are set to make it easier to pass them to and return them from methods.

### CODE REVIEW

**Comment by dmehring** [comment]
@mpokorny Hi Martin, Along with looking at the one line change I mentioned a few days ago in PR 690, I'd greatly appreciate it if you could also review this one which I submitted about a week and a half ago. I have other work in the queue which depends upon it.
Thanks

**Comment by mpokorny** [comment]
David, have you tried running your test code under valgrind (or similar tool) to check for memory leaks? I don't see any obvious issues, but it might be worth your time to try something like that (if you haven't already done so.)

**Comment by dmehring** [comment]
Hi Martin,
I always use smart pointers precisely to avoid memory leaks. Do you see any bare pointers allocated with new in my code? Because there shouldn't be.

**Comment by mpokorny** [comment]
No, I don't see any problems, my question was not specifically in reference to this PR. I agree that you should use smart pointers, but it's nice to do a test for leaks occasionally -- even when using smart pointer there could still be leaks (e.g, circular references).

**Comment by dmehring** [comment]
Hi Martin
I don't routinely run valgrind. I agree it is not a bad idea to do so, although my preference would be that it be done periodically as part of automated CI, if possible. It seems to me that would be a much better approach than to rely/expect developers to do it periodically, since it is a non-trivial thing to do and I suspect it could be automated and all casacore/casa C++ could be run using it in such an environment.
Thanks for the reviews today.

**Comment by mpokorny** [comment]
FYI, there's some discussion about valgrind running in the CI build in #675.

**Pull request merged**
