### PR TITLE
13921

### PR DESCRIPTION
**Pull request by dmehring**

### CODE REVIEW

**Comment by dpetry** [comment]
@tammojan , @dmehring , sorry, after all, I don't know much about Apple builds and cannot give a good review here.

**Comment by tammojan** [comment]
I believe that these changes fix the build, but I don't see how. Could you perhaps explain it to me?
Also, if this linking is just necessary for CASA, perhaps you could move it inside the `if (CASABUILD)`.

**Comment by dmehring** [comment]
I'm closing this PR and opening another for a branch rename, where I've included the if (CASA_BUILD) guard as requested

**Comment by dmehring** [comment]
I'm closing this PR and opening another for a branch rename, where I've included the if (CASA_BUILD) guard as requested

**Pull request closed without merging**
