### PR TITLE
Remove mirlib and MIRIADImage

### LINKED ISSUE #1344: Compilation fails with GCC 14
When building with gcc 14, casacore fails to compile `mirlib/uvio.c` because of a mismatch between int pointer types `(int8 *)`, required as the third argument of the function `rdhdl_c`, and `(off_t *)` .

```log
[   87s] FAILED: mirlib/CMakeFiles/casa_mirlib.dir/uvio.c.o 
[   87s] /usr/bin/gcc -DCFITSIO_VERSION_MAJOR=4 -DCFITSIO_VERSION_MINOR=300 -DHAVE_DYSCO -DHAVE_FFTW3 -DHAVE_FFTW3_THREADS -DHAVE_HDF5 -DHAVE_READLINE -DUSE_THREADS -DWCSLIB_VERSION_MAJOR=8 -DWCSLIB_VERSION_MINOR=2 -Dcasa_mirlib_EXPORTS -I/home/abuild/rpmbuild/BUILD/casacore-3.5.0 -I/home/abuild/rpmbuild/BUILD/casacore-3.5.0/build -I/usr/include/cfitsio -fcx-fortran-rules -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fopenmp -pthread -O2 -g -DNDEBUG -fPIC -MD -MT mirlib/CMakeFiles/casa_mirlib.dir/uvio.c.o -MF mirlib/CMakeFiles/casa_mirlib.dir/uvio.c.o.d -o mirlib/CMakeFiles/casa_mirlib.dir/uvio.c.o -c /home/abuild/rpmbuild/BUILD/casacore-3.5.0/mirlib/uvio.c
[   87s] /home/abuild/rpmbuild/BUILD/casacore-3.5.0/mirlib/uvio.c: In function ‘uvopen_c’:
[   87s] /home/abuild/rpmbuild/BUILD/casacore-3.5.0/mirlib/uvio.c:794:29: error: passing argument 3 of ‘rdhdl_c’ from incompatible pointer type [-Wincompatible-pointer-types]
[   87s]   794 |       rdhdl_c(*tno,"vislen",&(uv->offset),hsize_c(uv->item));
[   87s]       |                             ^~~~~~~~~~~~~
[   87s]       |                             |
--
[   87s] /home/abuild/rpmbuild/BUILD/casacore-3.5.0/mirlib/miriad.h:182:51: note: expected ‘int8 *’ {aka ‘long long int *’} but argument is of type ‘off_t *’ {aka ‘long int *’}
[   87s]   182 | void rdhdl_c (int tno, Const char *keyword, int8 *value, int8 defval);
[   87s]       |                                             ~~~~~~^~~~~
[   87s] /home/abuild/rpmbuild/BUILD/casacore-3.5.0/mirlib/uvio.c:814:26: error: passing argument 3 of ‘rdhdl_c’ from incompatible pointer type [-Wincompatible-pointer-types]
[   87s]   814 |     rdhdl_c(*tno,"ncorr",&(uv->corr_flags.offset),-1);
[   87s]       |                          ^~~~~~~~~~~~~~~~~~~~~~~~
[   87s]       |                          |
--
[   87s] /home/abuild/rpmbuild/BUILD/casacore-3.5.0/mirlib/miriad.h:182:51: note: expected ‘int8 *’ {aka ‘long long int *’} but argument is of type ‘off_t *’ {aka ‘long int *’}
[   87s]   182 | void rdhdl_c (int tno, Const char *keyword, int8 *value, int8 defval);
[   87s]       |                                             ~~~~~~^~~~~
[   87s] /home/abuild/rpmbuild/BUILD/casacore-3.5.0/mirlib/uvio.c:815:27: error: passing argument 3 of ‘rdhdl_c’ from incompatible pointer type [-Wincompatible-pointer-types]
[   87s]   815 |     rdhdl_c(*tno,"nwcorr",&(uv->wcorr_flags.offset),-1);
[   87s]       |                           ^~~~~~~~~~~~~~~~~~~~~~~~~
[   87s]       |                           |
```

### PR DESCRIPTION
**Pull request by aroffringa**
This code seems unused and no longer compiles under gcc 14. After these changes, casacore compiles without errors when using gcc 14.

Fixes #1344.

### CODE REVIEW

**Comment by badshah400** [comment]
Hi, just tried this. `cmake install` fails, because you probably also need this (or perhaps I made some error in rebasing your patch against casacore version 3.5.0):

```diff
Index: casacore-3.5.0/images/CMakeLists.txt
===================================================================
--- casacore-3.5.0.orig/images/CMakeLists.txt
+++ casacore-3.5.0/images/CMakeLists.txt
@@ -123,7 +121,6 @@ Images/ImageSummary.tcc
 Images/ImageUtilities.h
 Images/ImageUtilities2.tcc
 Images/LELImageCoord.h
-Images/MIRIADImage.h
 Images/MaskSpecifier.h
 Images/PagedImage.h
 Images/PagedImage.tcc
```

**Comment by aroffringa** [comment]
> Hi, just tried this. `cmake install` fails, because you probably also need this (or perhaps I made some error in rebasing your patch against casacore version 3.5.0):
> ```
Thanks, seems like I missed that reference. Should be fixed now.

**Review by schiebel — CHANGES_REQUESTED** [review]
CASA uses MIRIADImage and mirlib. Coordination is required to either remove this dependency or move this code to CASA before this PR should be merged.

**Comment by cquike** [comment]
Copying the code to CASA will shift the problem of the gcc 14 issue #1344. As @aroffringa pointed out the code might have already been broken at runtime and in that case CASA would import broken code at runtime. @schiebel : if I remember correctly from last CASA infrastructure meeting it was mentioned that miriad format is still used by some users, is that correct?

**Comment by badshah400** [comment]
Probably should open an issue over at [python-casacore](https://github.com/casacore/python-casacore) but just mentioning here for bookkeeping purposes that python-casacore also needs a patch to disable `mirlib` support. For openSUSE's python-casacore packages to build against a version of casacore with this PR applied, we had to apply:

```diff
---
 src/images.cc |    4 +---
 1 file changed, 1 insertion(+), 3 deletions(-)

Index: python-casacore-3.5.2/src/images.cc
===================================================================
--- python-casacore-3.5.2.orig/src/images.cc
+++ python-casacore-3.5.2/src/images.cc
@@ -34,7 +34,6 @@
 
 #include <casacore/images/Images/ImageProxy.h>
 #include <casacore/images/Images/FITSImage.h>
-#include <casacore/images/Images/MIRIADImage.h>
 
 #include <boost/python.hpp>
 
@@ -47,9 +46,8 @@ BOOST_PYTHON_MODULE(_images)
   casacore::python::register_convert_casa_record();
   casacore::python::register_convert_std_vector<casacore::ImageProxy>();
 
-  // Register the FITS and Miriad image types.
+  // Register the FITS type.
   casacore::FITSImage::registerOpenFunction();
-  casacore::MIRIADImage::registerOpenFunction();
 
   // Make python interface to images.
   casacore::python::pyimages();
Index: python-casacore-3.5.2/setup.py
===================================================================
--- python-casacore-3.5.2.orig/setup.py
+++ python-casacore-3.5.2/setup.py
@@ -180,7 +180,7 @@ def get_extensions():
             ["src/pyimages.h"],
             ['casa_images', 'casa_coordinates',
              'casa_fits', 'casa_lattices', 'casa_measures',
-             'casa_scimath', 'casa_scimath_f', 'casa_tables', 'casa_mirlib',
+             'casa_scimath', 'casa_scimath_f', 'casa_tables',
              boost_python_libname, casa_python_libname]
         ),
         (
```

**Comment by schiebel** [comment]
I had assumed that a pointer was being used because a number of `int8` were being set. However, it now seems like this is code generated with an F2C converter and only a **single** `int8` is being assigned. This means that a simple pointer cast would have resolved the issue for little endian architectures.

I would propose [this change](https://github.com/casacore/casacore/compare/master...fix-gcc14-compile) as a resolution to #1344

**Pull request closed without merging**
