### PR TITLE
disable python3 for osx, install gfortran for osx

### PR DESCRIPTION
**Pull request by gijzelaerr**

### CODE REVIEW

**Comment by tammojan** [comment]
The test says `make: gfortran: No such file or directory`, see https://travis-ci.org/casacore/casacore/jobs/172578517#L96

**Comment by gijzelaerr** [comment]
probably because the osx Cellar is cached. not sure how to remove that cache? I didn't set that up.

**Comment by juliantaylor** [comment]
in the travis ui there is a more options tab, under there is the caches folder where you can delete caches. I have removed all caches and restarted, lets hope it finishes within the timeout without a cache.

**Comment by juliantaylor** [comment]
and it fails, apparently it is in gcc instead of gfortran.

**Comment by tammojan** [comment]
Yes it should be gcc. Sorry for not noticing earlier, I did this in #507 (which I'll close in favor of Gijs' better attempt).

**Comment by juliantaylor** [comment]
this PR is also not turning of python3 in `.travis/before_install.sh`

**Comment by gijzelaerr** [comment]
sorry guys, this week i'm moving back to south africa so I can't look into this. @tammojan can you pick this up?

**Comment by juliantaylor** [comment]
looks like the mac non c++11 build is too slow now, maybe the new clang is slower.
Things we could try:

set optimization level to 1 for this build, maybe it is fast enough, disable this build or bootstrap the cache via only partially building casacore.

**Comment by juliantaylor** [comment]
also tConvert is failing in the new mac, I saw it fail on ubuntu machines with stack smashing errors, not sure if mac has the same issue. Verbose builds might be useful.

**Comment by tammojan** [comment]
Apparently a problem with Boost Python on OSX, maybe linking against wrong python version or someting. To be investigated..

**Comment by tammojan** [comment]
Superseded by #654.

**Pull request closed without merging**
